
var h;h||(h=typeof Module !== 'undefined' ? Module : {});h.lf||(h.lf=0);h.lf++;
(function(a){function b(n,r,q){var t=new XMLHttpRequest;t.open("GET",n,!0);t.responseType="arraybuffer";t.onprogress=function(u){var v=r;u.total&&(v=u.total);if(u.loaded){t.ne?h.Ge[n].loaded=u.loaded:(t.ne=!0,h.Ge||(h.Ge={}),h.Ge[n]={loaded:u.loaded,total:v});var B=v=u=0,x;for(x in h.Ge){var F=h.Ge[x];u+=F.total;v+=F.loaded;B++}u=Math.ceil(u*h.lf/B);h.setStatus&&h.setStatus("Downloading data... ("+v+"/"+u+")")}else!h.Ge&&h.setStatus&&h.setStatus("Downloading data...")};t.onerror=function(){throw Error("NetworkError for: "+
n);};t.onload=function(){if(200==t.status||304==t.status||206==t.status||0==t.status&&t.response)q(t.response);else throw Error(t.statusText+" : "+t.responseURL);};t.send(null)}function c(n){console.error("package error:",n)}function d(){function n(u,v,B){this.start=u;this.end=v;this.audio=B}function r(u){if(!u)throw"Loading data file failed."+Error().stack;if(!(u instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;u=new Uint8Array(u);n.prototype.Hf=u;u=a.files;for(var v=
0;v<u.length;++v)n.prototype.ne[u[v].filename].onload();h.removeRunDependency("datafile_index.data")}n.prototype={ne:{},open:function(u,v){this.name=v;this.ne[v]=this;h.addRunDependency("fp "+this.name)},send:function(){},onload:function(){this.Oe(this.Hf.subarray(this.start,this.end))},Oe:function(u){h.FS_createDataFile(this.name,null,u,!0,!0,!0);h.removeRunDependency("fp "+this.name);this.ne[this.name]=null}};for(var q=a.files,t=0;t<q.length;++t)(new n(q[t].start,q[t].end,q[t].audio)).open("GET",
q[t].filename);h.addRunDependency("datafile_index.data");h.Qf||(h.Qf={});h.Qf["index.data"]={Fg:!1};m?(r(m),m=null):g=r}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");else throw"using preloaded data can only be done on a web page or in a web worker";
"function"!==typeof h.locateFilePackage||h.locateFile||(h.locateFile=h.locateFilePackage,k("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=h.locateFile?h.locateFile("index.data",""):"index.data",f=a.remote_package_size,g=null,m=h.getPreloadedPackage?h.getPreloadedPackage(e,f):null;m||b(e,f,function(n){g?(g(n),g=null):m=n},c);h.calledRun?d():(h.preRun||(h.preRun=[]),h.preRun.push(d))})({files:[{filename:"/ocean.pd",
start:0,end:2209,audio:0}],remote_package_size:2209,package_uuid:"5c54488a-de6a-4fb4-8ba5-5aa61297fa5a"});var aa={},ba;for(ba in h)h.hasOwnProperty(ba)&&(aa[ba]=h[ba]);var ca=[],da="./this.program";function ea(a,b){throw b;}var fa=!1,ha=!1,ia=!1,ja=!1;fa="object"===typeof window;ha="function"===typeof importScripts;ia="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ja=!fa&&!ia&&!ha;var ka="",la,na,oa,pa,qa,ra;
if(ia)ka=ha?require("path").dirname(ka)+"/":__dirname+"/",la=function(a,b){qa||(qa=require("fs"));ra||(ra=require("path"));a=ra.normalize(a);return qa.readFileSync(a,b?null:"utf8")},oa=function(a){a=la(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/")),ca=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=h),process.on("uncaughtException",function(a){if(!(a instanceof sa))throw a;}),process.on("unhandledRejection",
l),ea=function(a){process.exit(a)},h.inspect=function(){return"[Emscripten Module object]"};else if(ja)"undefined"!=typeof read&&(la=function(a){return read(a)}),oa=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ca=scriptArgs:"undefined"!=typeof arguments&&(ca=arguments),"function"===typeof quit&&(ea=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&
(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(fa||ha)ha?ka=self.location.href:"undefined"!==typeof document&&document.currentScript&&(ka=document.currentScript.src),ka=0!==ka.indexOf("blob:")?ka.substr(0,ka.lastIndexOf("/")+1):"",la=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ha&&(oa=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
na=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},pa=function(a){document.title=a};var ta=h.print||console.log.bind(console),k=h.printErr||console.warn.bind(console);for(ba in aa)aa.hasOwnProperty(ba)&&(h[ba]=aa[ba]);aa=null;h.arguments&&(ca=h.arguments);h.thisProgram&&(da=h.thisProgram);h.quit&&(ea=h.quit);
function ua(a){va||(va={});va[a]||(va[a]=1,k(a))}var va,wa;h.wasmBinary&&(wa=h.wasmBinary);var noExitRuntime=h.noExitRuntime||!0;"object"!==typeof WebAssembly&&l("no native wasm support detected");
function xa(a,b){var c="float";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":p[a>>0]=b;break;case "i8":p[a>>0]=b;break;case "i16":ya[a>>1]=b;break;case "i32":w[a>>2]=b;break;case "i64":y=[b>>>0,(z=b,1<=+Math.abs(z)?0<z?(Math.min(+Math.floor(z/4294967296),4294967295)|0)>>>0:~~+Math.ceil((z-+(~~z>>>0))/4294967296)>>>0:0)];w[a>>2]=y[0];w[a+4>>2]=y[1];break;case "float":A[a>>2]=b;break;case "double":za[a>>3]=b;break;default:l("invalid type for setValue: "+c)}}var Aa,Ba=!1,Ca;
function assert(a,b){a||l("Assertion failed: "+b)}var Da="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Ea(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Da)return Da.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function C(a,b){return a?Ea(D,a,b):""}
function Fa(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var m=a.charCodeAt(++f);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e}function G(a,b,c){return Fa(a,D,b,c)}
function Ga(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Ha(a){var b=Ga(a)+1,c=H(b);c&&Fa(a,p,c,b);return c}function Ia(a){var b=Ga(a)+1,c=Ja(b);Fa(a,p,c,b);return c}function Ka(a,b){for(var c=0;c<a.length;++c)p[b++>>0]=a.charCodeAt(c);p[b>>0]=0}var La,p,D,ya,Ma,w,Na,A,za,I,Oa=[],Pa=[],Qa=[],Ra=[],Sa=[];function Ta(){var a=h.preRun.shift();Oa.unshift(a)}
var Ua=0,Va=null,Wa=null;function Xa(){Ua++;h.monitorRunDependencies&&h.monitorRunDependencies(Ua)}function Ya(){Ua--;h.monitorRunDependencies&&h.monitorRunDependencies(Ua);if(0==Ua&&(null!==Va&&(clearInterval(Va),Va=null),Wa)){var a=Wa;Wa=null;a()}}h.preloadedImages={};h.preloadedAudios={};function l(a){if(h.onAbort)h.onAbort(a);k(a);Ba=!0;Ca=1;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}
function Za(){return $a.startsWith("data:application/octet-stream;base64,")}var $a="index.wasm";if(!Za()){var ab=$a;$a=h.locateFile?h.locateFile(ab,ka):ka+ab}function bb(){var a=$a;try{if(a==$a&&wa)return new Uint8Array(wa);if(oa)return oa(a);throw"both async and sync fetching of the wasm failed";}catch(b){l(b)}}
function cb(){if(!wa&&(fa||ha)){if("function"===typeof fetch&&!$a.startsWith("file://"))return fetch($a,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+$a+"'";return a.arrayBuffer()}).catch(function(){return bb()});if(na)return new Promise(function(a,b){na($a,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return bb()})}
var z,y,fb={98804:function(a,b,c){h.SDL2||(h.SDL2={});var d=h.SDL2;d.Yf!==h.canvas&&(d.ze=h.createContext(h.canvas,!1,!0),d.Yf=h.canvas);if(d.w!==a||d.hg!==b||d.kg!==d.ze)d.image=d.ze.createImageData(a,b),d.w=a,d.hg=b,d.kg=d.ze;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=w[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.Dg!==a&&(d.$f=new Int32Array(a.buffer),d.ag=new Uint8Array(a.buffer)),
a=d.$f,c=a.length,a.set(w.subarray(b,b+c)),a=d.ag,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.ze.putImageData(d.image,0,0);return 0},100259:function(a,b,c,d,e){var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e>>=2;var m=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof
CanvasPixelArray)for(n=b.length;m<n;){var r=w[e];b[m]=r&255;b[m+1]=r>>8&255;b[m+2]=r>>16&255;b[m+3]=r>>24&255;e++;m+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(w.subarray(e,e+n));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=H(c.length+1);G(c,d,c.length+1);return d},101248:function(a){h.canvas&&(h.canvas.style.cursor=C(a));return 0},101341:function(){h.canvas&&(h.canvas.style.cursor="none")},101410:function(){return screen.width},
101435:function(){return screen.height},101461:function(){return window.innerWidth},101491:function(){return window.innerHeight},101522:function(a){"undefined"!==typeof pa&&pa(C(a));return 0},101617:function(){return"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?1:0},101754:function(){return"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?1:0},101978:function(a){"undefined"===
typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.le||("undefined"!==typeof AudioContext?b.le=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.le=new webkitAudioContext),b.le&&db(b.le));return void 0===b.le?-1:0},102471:function(){return h.SDL2.le.sampleRate},102539:function(a,b,c,d){function e(){}function f(m){void 0!==g.capture.Re&&(clearTimeout(g.capture.Re),g.capture.Re=void 0);g.capture.bf=g.le.createMediaStreamSource(m);g.capture.qe=g.le.createScriptProcessor(b,
a,1);g.capture.qe.onaudioprocess=function(n){void 0!==g&&void 0!==g.capture&&(n.outputBuffer.getChannelData(0).fill(0),g.capture.kf=n.inputBuffer,eb(c,[d]))};g.capture.bf.connect(g.capture.qe);g.capture.qe.connect(g.le.destination);g.capture.stream=m}var g=h.SDL2;g.capture.gf=g.le.createBuffer(a,b,g.le.sampleRate);g.capture.gf.getChannelData(0).fill(0);g.capture.Re=setTimeout(function(){g.capture.kf=g.capture.gf;eb(c,[d])},b/g.le.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?
navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},104191:function(a,b,c,d){var e=h.SDL2;e.audio.qe=e.le.createScriptProcessor(b,0,a);e.audio.qe.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(e.audio.Bf=f.outputBuffer,eb(c,[d]))};e.audio.qe.connect(e.le.destination)},104601:function(a,b){for(var c=h.SDL2,d=c.capture.kf.numberOfChannels,e=0;e<d;++e){var f=c.capture.kf.getChannelData(e);
if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var g=0;g<b;++g)xa(a+4*g,f[g]);else for(g=0;g<b;++g)xa(a+4*(g*d+e),f[g])}},105206:function(a,b){for(var c=h.SDL2,d=c.audio.Bf.numberOfChannels,e=0;e<d;++e){var f=c.audio.Bf.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=A[a+(g*d+e<<2)>>
2]}},105686:function(a){var b=h.SDL2;if(a){void 0!==b.capture.Re&&clearTimeout(b.capture.Re);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);b.capture.stream=void 0}void 0!==b.capture.qe&&(b.capture.qe.onaudioprocess=function(){},b.capture.qe.disconnect(),b.capture.qe=void 0);void 0!==b.capture.bf&&(b.capture.bf.disconnect(),b.capture.bf=void 0);void 0!==b.capture.gf&&(b.capture.gf=void 0);b.capture=void 0}else void 0!=
b.audio.qe&&(b.audio.qe.disconnect(),b.audio.qe=void 0),b.audio=void 0;void 0!==b.le&&void 0===b.audio&&void 0===b.capture&&(b.le.close(),b.le=void 0)}};function gb(a,b,c){a.addEventListener(b,c,{once:!0})}function db(a){var b;b||(b=[document,document.getElementById("canvas")]);["keydown","mousedown","touchstart"].forEach(function(c){b.forEach(function(d){d&&gb(d,c,function(){"suspended"===a.state&&a.resume()})})})}
function hb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(h);else{var c=b.fg;"number"===typeof c?void 0===b.Te?I.get(c)():I.get(c)(b.Te):c(void 0===b.Te?null:b.Te)}}}function eb(a,b){if("vi".includes("j")){var c=h.dynCall_vi;b&&b.length?c.apply(null,[a].concat(b)):c.call(null,a)}else I.get(a).apply(null,b)}
function ib(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function jb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=ib(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function kb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function lb(a){if("/"===a)return"/";a=jb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function mb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(ia)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){l("randomDevice")}}
function nb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=ib(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var ob=[];function pb(a,b){ob[a]={input:[],output:[],Ie:b};qb(a,rb)}
var rb={open:function(a){var b=ob[a.node.rdev];if(!b)throw new J(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.Ie.flush(a.tty)},flush:function(a){a.tty.Ie.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Ie.Ff)throw new J(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.Ie.Ff(a.tty)}catch(m){throw new J(29);}if(void 0===g&&0===e)throw new J(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.Ie.pf)throw new J(60);
try{for(var e=0;e<d;e++)a.tty.Ie.pf(a.tty,b[c+e])}catch(f){throw new J(29);}d&&(a.node.timestamp=Date.now());return e}},tb={Ff:function(a){if(!a.input.length){var b=null;if(ia){var c=Buffer.ne?Buffer.ne(256):new Buffer(256),d=0;try{d=qa.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(e.toString().includes("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=sb(b)}return a.input.shift()},pf:function(a,b){null===b||10===b?(ta(Ea(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ta(Ea(a.output,0)),a.output=[])}},ub={pf:function(a,b){null===b||10===b?(k(Ea(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(k(Ea(a.output,0)),a.output=[])}},K={Ce:null,Be:function(){return K.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new J(63);K.Ce||(K.Ce={dir:{node:{Ae:K.he.Ae,se:K.he.se,lookup:K.he.lookup,cf:K.he.cf,rename:K.he.rename,unlink:K.he.unlink,rmdir:K.he.rmdir,readdir:K.he.readdir,symlink:K.he.symlink},stream:{Fe:K.ge.Fe}},file:{node:{Ae:K.he.Ae,se:K.he.se},stream:{Fe:K.ge.Fe,read:K.ge.read,write:K.ge.write,wf:K.ge.wf,Lf:K.ge.Lf,Nf:K.ge.Nf}},link:{node:{Ae:K.he.Ae,se:K.he.se,readlink:K.he.readlink},stream:{}},Af:{node:{Ae:K.he.Ae,
se:K.he.se},stream:vb}});c=wb(a,b,c,d);L(c.mode)?(c.he=K.Ce.dir.node,c.ge=K.Ce.dir.stream,c.fe={}):32768===(c.mode&61440)?(c.he=K.Ce.file.node,c.ge=K.Ce.file.stream,c.je=0,c.fe=null):40960===(c.mode&61440)?(c.he=K.Ce.link.node,c.ge=K.Ce.link.stream):8192===(c.mode&61440)&&(c.he=K.Ce.Af.node,c.ge=K.Ce.Af.stream);c.timestamp=Date.now();a&&(a.fe[b]=c,a.timestamp=c.timestamp);return c},Gg:function(a){return a.fe?a.fe.subarray?a.fe.subarray(0,a.je):new Uint8Array(a.fe):new Uint8Array(0)},Cf:function(a,
b){var c=a.fe?a.fe.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.fe,a.fe=new Uint8Array(b),0<a.je&&a.fe.set(c.subarray(0,a.je),0))},sg:function(a,b){if(a.je!=b)if(0==b)a.fe=null,a.je=0;else{var c=a.fe;a.fe=new Uint8Array(b);c&&a.fe.set(c.subarray(0,Math.min(b,a.je)));a.je=b}},he:{Ae:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;L(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.je:
40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Xf=4096;b.blocks=Math.ceil(b.size/b.Xf);return b},se:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&K.sg(a,b.size)},lookup:function(){throw xb[44];},cf:function(a,b,c,d){return K.createNode(a,b,c,d)},rename:function(a,b,c){if(L(a.mode)){try{var d=yb(b,c)}catch(f){}if(d)for(var e in d.fe)throw new J(55);
}delete a.parent.fe[a.name];a.parent.timestamp=Date.now();a.name=c;b.fe[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.fe[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=yb(a,b),d;for(d in c.fe)throw new J(55);delete a.fe[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.fe)a.fe.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=K.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new J(28);
return a.link}},ge:{read:function(a,b,c,d,e){var f=a.node.fe;if(e>=a.node.je)return 0;a=Math.min(a.node.je-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.fe||a.fe.subarray)){if(f)return a.fe=b.subarray(c,c+d),a.je=d;if(0===a.je&&0===e)return a.fe=b.slice(c,c+d),a.je=d;if(e+d<=a.je)return a.fe.set(b.subarray(c,c+d),e),d}K.Cf(a,e+d);if(a.fe.subarray&&b.subarray)a.fe.set(b.subarray(c,
c+d),e);else for(f=0;f<d;f++)a.fe[e+f]=b[c+f];a.je=Math.max(a.je,e+d);return d},Fe:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.je);if(0>b)throw new J(28);return b},wf:function(a,b,c){K.Cf(a.node,b+c);a.node.je=Math.max(a.node.je,b+c)},Lf:function(a,b,c,d,e,f){if(0!==b)throw new J(28);if(32768!==(a.node.mode&61440))throw new J(43);a=a.node.fe;if(f&2||a.buffer!==La){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;
f=65536*Math.ceil(c/65536);for(b=H(f);c<f;)p[b+c++]=0;c=b;if(!c)throw new J(48);p.set(a,c)}else d=!1,c=a.byteOffset;return{Pg:c,zg:d}},Nf:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new J(43);if(e&2)return 0;K.ge.write(a,b,0,d,c,!1);return 0}}},zb=null,Ab={},Bb=[],Cb=1,Db=null,Eb=!0,Fb={},J=null,xb={};
function Gb(a,b){a=nb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Df:!0,qf:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.qf)throw new J(32);a=ib(a.split("/").filter(function(g){return!!g}),!1);var e=zb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=yb(e,a[d]);c=jb(c+"/"+a[d]);e.Pe&&(!f||f&&b.Df)&&(e=e.Pe.root);if(!f||b.Ne)for(f=0;40960===(e.mode&61440);)if(e=Hb(c),c=nb(kb(c),e),e=Gb(c,{qf:b.qf}).node,40<f++)throw new J(32);}return{path:c,node:e}}
function Ib(a){for(var b;;){if(a===a.parent)return a=a.Be.Mf,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Jb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Db.length}function yb(a,b){var c;if(c=(c=Kb(a,"x"))?c:a.he.lookup?0:2)throw new J(c,a);for(c=Db[Jb(a.id,b)];c;c=c.He){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.he.lookup(a,b)}
function wb(a,b,c,d){a=new Lb(a,b,c,d);b=Jb(a.parent.id,a.name);a.He=Db[b];return Db[b]=a}function L(a){return 16384===(a&61440)}var Mb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function Nb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Kb(a,b){if(Eb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Ob(a,b){try{return yb(a,b),20}catch(c){}return Kb(a,"wx")}
function Pb(a,b){b=b||4096;for(a=a||0;a<=b;a++)if(!Bb[a])return a;throw new J(33);}function Qb(a,b,c){Rb||(Rb=function(){},Rb.prototype={});var d=new Rb,e;for(e in a)d[e]=a[e];a=d;b=Pb(b,c);a.fd=b;return Bb[b]=a}var vb={open:function(a){a.ge=Ab[a.node.rdev].ge;a.ge.open&&a.ge.open(a)},Fe:function(){throw new J(70);}};function qb(a,b){Ab[a]={ge:b}}
function Sb(a,b){var c="/"===b,d=!b;if(c&&zb)throw new J(10);if(!c&&!d){var e=Gb(b,{Df:!1});b=e.path;e=e.node;if(e.Pe)throw new J(10);if(!L(e.mode))throw new J(54);}b={type:a,Og:{},Mf:b,pg:[]};a=a.Be(b);a.Be=b;b.root=a;c?zb=a:e&&(e.Pe=b,e.Be&&e.Be.pg.push(b));return a}function Tb(a,b,c){var d=Gb(a,{parent:!0}).node;a=lb(a);if(!a||"."===a||".."===a)throw new J(28);var e=Ob(d,a);if(e)throw new J(e);if(!d.he.cf)throw new J(63);return d.he.cf(d,a,b,c)}function Ub(a){return Tb(a,16895,0)}
function Vb(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Tb(a,b|8192,c)}function Wb(a,b){if(!nb(a))throw new J(44);var c=Gb(b,{parent:!0}).node;if(!c)throw new J(44);b=lb(b);var d=Ob(c,b);if(d)throw new J(d);if(!c.he.symlink)throw new J(63);c.he.symlink(c,b,a)}
function Xb(a){var b=Gb(a,{parent:!0}).node,c=lb(a),d=yb(b,c);a:{try{var e=yb(b,c)}catch(g){e=g.ie;break a}var f=Kb(b,"wx");e=f?f:L(e.mode)?31:0}if(e)throw new J(e);if(!b.he.unlink)throw new J(63);if(d.Pe)throw new J(10);try{Fb.willDeletePath&&Fb.willDeletePath(a)}catch(g){k("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+g.message)}b.he.unlink(b,c);b=Jb(d.parent.id,d.name);if(Db[b]===d)Db[b]=d.He;else for(b=Db[b];b;){if(b.He===d){b.He=d.He;break}b=b.He}try{if(Fb.onDeletePath)Fb.onDeletePath(a)}catch(g){k("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+g.message)}}function Hb(a){a=Gb(a).node;if(!a)throw new J(44);if(!a.he.readlink)throw new J(28);return nb(Ib(a.parent),a.he.readlink(a))}function Yb(a,b){a="string"===typeof a?Gb(a,{Ne:!0}).node:a;if(!a.he.se)throw new J(63);a.he.se(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function Zb(a,b,c,d){if(""===a)throw new J(44);if("string"===typeof b){var e=Mb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=jb(a);try{f=Gb(a,{Ne:!(b&131072)}).node}catch(g){}}e=!1;if(b&64)if(f){if(b&128)throw new J(20);}else f=Tb(a,c,0),e=!0;if(!f)throw new J(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&!L(f.mode))throw new J(54);if(!e&&(c=f?40960===(f.mode&61440)?32:L(f.mode)&&
("r"!==Nb(b)||b&512)?31:Kb(f,Nb(b)):44))throw new J(c);if(b&512){c=f;c="string"===typeof c?Gb(c,{Ne:!0}).node:c;if(!c.he.se)throw new J(63);if(L(c.mode))throw new J(31);if(32768!==(c.mode&61440))throw new J(28);if(e=Kb(c,"w"))throw new J(e);c.he.se(c,{size:0,timestamp:Date.now()})}b&=-131713;d=Qb({node:f,path:Ib(f),flags:b,seekable:!0,position:0,ge:f.ge,vg:[],error:!1},d,void 0);d.ge.open&&d.ge.open(d);!h.logReadFiles||b&1||($b||($b={}),a in $b||($b[a]=1,k("FS.trackingDelegate error on read file: "+
a)));try{Fb.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),Fb.onOpenFile(a,f))}catch(g){k("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+g.message)}return d}function ac(a){if(null===a.fd)throw new J(8);a.mf&&(a.mf=null);try{a.ge.close&&a.ge.close(a)}catch(b){throw b;}finally{Bb[a.fd]=null}a.fd=null}
function bc(a,b,c){if(null===a.fd)throw new J(8);if(!a.seekable||!a.ge.Fe)throw new J(70);if(0!=c&&1!=c&&2!=c)throw new J(28);a.position=a.ge.Fe(a,b,c);a.vg=[]}
function cc(a,b,c,d,e,f){if(0>d||0>e)throw new J(28);if(null===a.fd)throw new J(8);if(0===(a.flags&2097155))throw new J(8);if(L(a.node.mode))throw new J(31);if(!a.ge.write)throw new J(28);a.seekable&&a.flags&1024&&bc(a,0,2);var g="undefined"!==typeof e;if(!g)e=a.position;else if(!a.seekable)throw new J(70);b=a.ge.write(a,b,c,d,e,f);g||(a.position+=b);try{if(a.path&&Fb.onWriteToFile)Fb.onWriteToFile(a.path)}catch(m){k("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+m.message)}return b}
function fc(){J||(J=function(a,b){this.node=b;this.tg=function(c){this.ie=c};this.tg(a);this.message="FS error"},J.prototype=Error(),J.prototype.constructor=J,[44].forEach(function(a){xb[a]=new J(a);xb[a].stack="<generic error, no stack>"}))}var hc;function ic(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function jc(a,b){a="string"===typeof a?a:Ib(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=jb(a+"/"+c);try{Ub(d)}catch(e){}a=d}}return d}
function kc(a,b,c,d){a=jb(("string"===typeof a?a:Ib(a))+"/"+b);c=ic(c,d);return Tb(a,(void 0!==c?c:438)&4095|32768,0)}function lc(a,b,c,d,e,f){a=b?jb(("string"===typeof a?a:Ib(a))+"/"+b):a;d=ic(d,e);e=Tb(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var g=c.length;b<g;++b)a[b]=c.charCodeAt(b);c=a}Yb(e,d|146);a=Zb(e,577);cc(a,c,0,c.length,0,f);ac(a);Yb(e,d)}return e}
function mc(a,b,c,d){a=jb(("string"===typeof a?a:Ib(a))+"/"+b);b=ic(!!c,!!d);mc.Jf||(mc.Jf=64);var e=mc.Jf++<<8|0;qb(e,{open:function(f){f.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(f,g,m,n){for(var r=0,q=0;q<n;q++){try{var t=c()}catch(u){throw new J(29);}if(void 0===t&&0===r)throw new J(6);if(null===t||void 0===t)break;r++;g[m+q]=t}r&&(f.node.timestamp=Date.now());return r},write:function(f,g,m,n){for(var r=0;r<n;r++)try{d(g[m+r])}catch(q){throw new J(29);}n&&
(f.node.timestamp=Date.now());return r}});return Vb(a,b,e)}function nc(a){if(!(a.ng||a.og||a.link||a.fe)){if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(la)try{a.fe=sb(la(a.url)),a.je=a.fe.length}catch(b){throw new J(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function oc(a,b,c,d,e){function f(){this.nf=!1;this.ne=[]}f.prototype.get=function(q){if(!(q>this.length-1||0>q)){var t=q%this.chunkSize;return this.Gf(q/this.chunkSize|0)[t]}};f.prototype.Oe=function(q){this.Gf=q};f.prototype.yf=function(){var q=new XMLHttpRequest;q.open("HEAD",c,!1);q.send(null);if(!(200<=q.status&&300>q.status||304===q.status))throw Error("Couldn't load "+c+". Status: "+q.status);var t=Number(q.getResponseHeader("Content-length")),u,v=(u=q.getResponseHeader("Accept-Ranges"))&&
"bytes"===u;q=(u=q.getResponseHeader("Content-Encoding"))&&"gzip"===u;var B=1048576;v||(B=t);var x=this;x.Oe(function(F){var U=F*B,ma=(F+1)*B-1;ma=Math.min(ma,t-1);if("undefined"===typeof x.ne[F]){var R=x.ne;if(U>ma)throw Error("invalid range ("+U+", "+ma+") or no bytes requested!");if(ma>t-1)throw Error("only "+t+" bytes available! programmer error!");var E=new XMLHttpRequest;E.open("GET",c,!1);t!==B&&E.setRequestHeader("Range","bytes="+U+"-"+ma);"undefined"!=typeof Uint8Array&&(E.responseType="arraybuffer");
E.overrideMimeType&&E.overrideMimeType("text/plain; charset=x-user-defined");E.send(null);if(!(200<=E.status&&300>E.status||304===E.status))throw Error("Couldn't load "+c+". Status: "+E.status);U=void 0!==E.response?new Uint8Array(E.response||[]):sb(E.responseText||"");R[F]=U}if("undefined"===typeof x.ne[F])throw Error("doXHR failed!");return x.ne[F]});if(q||!t)B=t=1,B=t=this.Gf(0).length,ta("LazyFiles on gzip forces download of the whole file when length is accessed");this.Wf=t;this.Vf=B;this.nf=
!0};if("undefined"!==typeof XMLHttpRequest){if(!ha)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var g=new f;Object.defineProperties(g,{length:{get:function(){this.nf||this.yf();return this.Wf}},chunkSize:{get:function(){this.nf||this.yf();return this.Vf}}});var m=void 0}else m=c,g=void 0;var n=kc(a,b,d,e);g?n.fe=g:m&&(n.fe=null,n.url=m);Object.defineProperties(n,{je:{get:function(){return this.fe.length}}});var r={};Object.keys(n.ge).forEach(function(q){var t=
n.ge[q];r[q]=function(){nc(n);return t.apply(null,arguments)}});r.read=function(q,t,u,v,B){nc(n);q=q.node.fe;if(B>=q.length)return 0;v=Math.min(q.length-B,v);if(q.slice)for(var x=0;x<v;x++)t[u+x]=q[B+x];else for(x=0;x<v;x++)t[u+x]=q.get(B+x);return v};n.ge=r;return n}
function pc(a,b,c,d,e,f,g,m,n,r){function q(v){function B(F){r&&r();m||lc(a,b,F,d,e,n);f&&f();Ya(u)}var x=!1;h.preloadPlugins.forEach(function(F){!x&&F.canHandle(t)&&(F.handle(v,t,B,function(){g&&g();Ya(u)}),x=!0)});x||B(v)}qc();var t=b?nb(jb(a+"/"+b)):a,u="cp "+t;Xa(u);"string"==typeof c?rc(c,function(v){q(v)},g):q(c)}var M={},Rb,$b;
function sc(a,b){try{var c=Gb(a,{Ne:!0}).node;if(!c)throw new J(44);if(!c.he.Ae)throw new J(63);var d=c.he.Ae(c)}catch(e){if(e&&e.node&&jb(a)!==jb(Ib(e.node)))return-54;throw e;}w[b>>2]=d.dev;w[b+4>>2]=0;w[b+8>>2]=d.ino;w[b+12>>2]=d.mode;w[b+16>>2]=d.nlink;w[b+20>>2]=d.uid;w[b+24>>2]=d.gid;w[b+28>>2]=d.rdev;w[b+32>>2]=0;y=[d.size>>>0,(z=d.size,1<=+Math.abs(z)?0<z?(Math.min(+Math.floor(z/4294967296),4294967295)|0)>>>0:~~+Math.ceil((z-+(~~z>>>0))/4294967296)>>>0:0)];w[b+40>>2]=y[0];w[b+44>>2]=y[1];
w[b+48>>2]=4096;w[b+52>>2]=d.blocks;w[b+56>>2]=d.atime.getTime()/1E3|0;w[b+60>>2]=0;w[b+64>>2]=d.mtime.getTime()/1E3|0;w[b+68>>2]=0;w[b+72>>2]=d.ctime.getTime()/1E3|0;w[b+76>>2]=0;y=[d.ino>>>0,(z=d.ino,1<=+Math.abs(z)?0<z?(Math.min(+Math.floor(z/4294967296),4294967295)|0)>>>0:~~+Math.ceil((z-+(~~z>>>0))/4294967296)>>>0:0)];w[b+80>>2]=y[0];w[b+84>>2]=y[1];return 0}var tc=void 0;function uc(){tc+=4;return w[tc-4>>2]}function vc(a){a=Bb[a];if(!a)throw new J(8);return a}
var N={Be:function(){h.websocket=h.websocket&&"object"===typeof h.websocket?h.websocket:{};h.websocket.hf={};h.websocket.on=function(a,b){"function"===typeof b&&(this.hf[a]=b);return this};h.websocket.emit=function(a,b){"function"===typeof this.hf[a]&&this.hf[a].call(this,b)};return wb(null,"/",16895,0)},createSocket:function(a,b,c){b&=-526337;c&&assert(1==b==(6==c));a={family:a,type:b,protocol:c,me:null,error:null,Qe:{},pending:[],Je:[],te:N.pe};b=N.ef();c=wb(N.root,b,49152,0);c.Ke=a;b=Qb({path:b,
node:c,flags:2,seekable:!1,ge:N.ge});a.stream=b;return a},gg:function(a){return(a=Bb[a])&&49152===(a.node.mode&49152)?a.node.Ke:null},ge:{ff:function(a){a=a.node.Ke;return a.te.ff(a)},Ye:function(a,b,c){a=a.node.Ke;return a.te.Ye(a,b,c)},read:function(a,b,c,d){a=a.node.Ke;d=a.te.Rf(a,d);if(!d)return 0;b.set(d.buffer,c);return d.buffer.length},write:function(a,b,c,d){a=a.node.Ke;return a.te.Tf(a,b,c,d)},close:function(a){a=a.node.Ke;a.te.close(a)}},ef:function(){N.ef.current||(N.ef.current=0);return"socket["+
N.ef.current++ +"]"},pe:{Ve:function(a,b,c){if("object"===typeof b){var d=b;c=b=null}if(d)if(d._socket)b=d._socket.remoteAddress,c=d._socket.remotePort;else{c=/ws[s]?:\/\/([^:]+):(\d+)/.exec(d.url);if(!c)throw Error("WebSocket URL must be in the format ws(s)://address:port");b=c[1];c=parseInt(c[2],10)}else try{var e=h.websocket&&"object"===typeof h.websocket,f="ws:#".replace("#","//");e&&"string"===typeof h.websocket.url&&(f=h.websocket.url);if("ws://"===f||"wss://"===f){var g=b.split("/");f=f+g[0]+
":"+c+"/"+g.slice(1).join("/")}g="binary";e&&"string"===typeof h.websocket.subprotocol&&(g=h.websocket.subprotocol);var m=void 0;"null"!==g&&(g=g.replace(/^ +| +$/g,"").split(/ *, */),m=ia?{protocol:g.toString()}:g);e&&null===h.websocket.subprotocol&&(m=void 0);d=new (ia?require("ws"):WebSocket)(f,m);d.binaryType="arraybuffer"}catch(n){throw new J(23);}b={ke:b,port:c,socket:d,We:[]};N.pe.vf(a,b);N.pe.ig(a,b);2===a.type&&"undefined"!==typeof a.Le&&b.We.push(new Uint8Array([255,255,255,255,112,111,
114,116,(a.Le&65280)>>8,a.Le&255]));return b},Xe:function(a,b,c){return a.Qe[b+":"+c]},vf:function(a,b){a.Qe[b.ke+":"+b.port]=b},Sf:function(a,b){delete a.Qe[b.ke+":"+b.port]},ig:function(a,b){function c(){h.websocket.emit("open",a.stream.fd);try{for(var f=b.We.shift();f;)b.socket.send(f),f=b.We.shift()}catch(g){b.socket.close()}}function d(f){if("string"===typeof f)f=(new TextEncoder).encode(f);else{assert(void 0!==f.byteLength);if(0==f.byteLength)return;f=new Uint8Array(f)}var g=e;e=!1;g&&10===
f.length&&255===f[0]&&255===f[1]&&255===f[2]&&255===f[3]&&112===f[4]&&111===f[5]&&114===f[6]&&116===f[7]?(f=f[8]<<8|f[9],N.pe.Sf(a,b),b.port=f,N.pe.vf(a,b)):(a.Je.push({ke:b.ke,port:b.port,data:f}),h.websocket.emit("message",a.stream.fd))}var e=!0;ia?(b.socket.on("open",c),b.socket.on("message",function(f,g){g.Ag&&d((new Uint8Array(f)).buffer)}),b.socket.on("close",function(){h.websocket.emit("close",a.stream.fd)}),b.socket.on("error",function(){a.error=14;h.websocket.emit("error",[a.stream.fd,a.error,
"ECONNREFUSED: Connection refused"])})):(b.socket.onopen=c,b.socket.onclose=function(){h.websocket.emit("close",a.stream.fd)},b.socket.onmessage=function(f){d(f.data)},b.socket.onerror=function(){a.error=14;h.websocket.emit("error",[a.stream.fd,a.error,"ECONNREFUSED: Connection refused"])})},ff:function(a){if(1===a.type&&a.me)return a.pending.length?65:0;var b=0,c=1===a.type?N.pe.Xe(a,a.re,a.xe):null;if(a.Je.length||!c||c&&c.socket.readyState===c.socket.CLOSING||c&&c.socket.readyState===c.socket.CLOSED)b|=
65;if(!c||c&&c.socket.readyState===c.socket.OPEN)b|=4;if(c&&c.socket.readyState===c.socket.CLOSING||c&&c.socket.readyState===c.socket.CLOSED)b|=16;return b},Ye:function(a,b,c){switch(b){case 21531:return b=0,a.Je.length&&(b=a.Je[0].data.length),w[c>>2]=b,0;default:return 28}},close:function(a){if(a.me){try{a.me.close()}catch(e){}a.me=null}for(var b=Object.keys(a.Qe),c=0;c<b.length;c++){var d=a.Qe[b[c]];try{d.socket.close()}catch(e){}N.pe.Sf(a,d)}return 0},bind:function(a,b,c){if("undefined"!==typeof a.rf||
"undefined"!==typeof a.Le)throw new J(28);a.rf=b;a.Le=c;if(2===a.type){a.me&&(a.me.close(),a.me=null);try{a.te.listen(a,0)}catch(d){if(!(d instanceof J))throw d;if(138!==d.ie)throw d;}}},connect:function(a,b,c){if(a.me)throw new J(138);if("undefined"!==typeof a.re&&"undefined"!==typeof a.xe){var d=N.pe.Xe(a,a.re,a.xe);if(d){if(d.socket.readyState===d.socket.CONNECTING)throw new J(7);throw new J(30);}}b=N.pe.Ve(a,b,c);a.re=b.ke;a.xe=b.port;throw new J(26);},listen:function(a){if(!ia)throw new J(138);
if(a.me)throw new J(28);var b=require("ws").Server;a.me=new b({host:a.rf,port:a.Le});h.websocket.emit("listen",a.stream.fd);a.me.on("connection",function(c){if(1===a.type){var d=N.createSocket(a.family,a.type,a.protocol);c=N.pe.Ve(d,c);d.re=c.ke;d.xe=c.port;a.pending.push(d);h.websocket.emit("connection",d.stream.fd)}else N.pe.Ve(a,c),h.websocket.emit("connection",a.stream.fd)});a.me.on("closed",function(){h.websocket.emit("close",a.stream.fd);a.me=null});a.me.on("error",function(){a.error=23;h.websocket.emit("error",
[a.stream.fd,a.error,"EHOSTUNREACH: Host is unreachable"])})},accept:function(a){if(!a.me)throw new J(28);var b=a.pending.shift();b.stream.flags=a.stream.flags;return b},Hg:function(a,b){if(b){if(void 0===a.re||void 0===a.xe)throw new J(53);b=a.re;a=a.xe}else b=a.rf||0,a=a.Le||0;return{ke:b,port:a}},Tf:function(a,b,c,d,e,f){if(2===a.type){if(void 0===e||void 0===f)e=a.re,f=a.xe;if(void 0===e||void 0===f)throw new J(17);}else e=a.re,f=a.xe;var g=N.pe.Xe(a,e,f);if(1===a.type){if(!g||g.socket.readyState===
g.socket.CLOSING||g.socket.readyState===g.socket.CLOSED)throw new J(53);if(g.socket.readyState===g.socket.CONNECTING)throw new J(6);}ArrayBuffer.isView(b)&&(c+=b.byteOffset,b=b.buffer);b=b.slice(c,c+d);if(2===a.type&&(!g||g.socket.readyState!==g.socket.OPEN))return g&&g.socket.readyState!==g.socket.CLOSING&&g.socket.readyState!==g.socket.CLOSED||(g=N.pe.Ve(a,e,f)),g.We.push(b),d;try{return g.socket.send(b),d}catch(m){throw new J(28);}},Rf:function(a,b){if(1===a.type&&a.me)throw new J(53);var c=a.Je.shift();
if(!c){if(1===a.type){if(a=N.pe.Xe(a,a.re,a.xe)){if(a.socket.readyState===a.socket.CLOSING||a.socket.readyState===a.socket.CLOSED)return null;throw new J(6);}throw new J(53);}throw new J(6);}var d=c.data.byteLength||c.data.length,e=c.data.byteOffset||0,f=c.data.buffer||c.data;b=Math.min(b,d);var g={buffer:new Uint8Array(f,e,b),ke:c.ke,port:c.port};1===a.type&&b<d&&(c.data=new Uint8Array(f,e+b,d-b),a.Je.unshift(c));return g}}};function wc(a){a=N.gg(a);if(!a)throw new J(8);return a}
function xc(a){a=a.split(".");for(var b=0;4>b;b++){var c=Number(a[b]);if(isNaN(c))return null;a[b]=c}return(a[0]|a[1]<<8|a[2]<<16|a[3]<<24)>>>0}
function yc(a){var b,c,d=[];if(!/^((?=.*::)(?!.*::.+::)(::)?([\dA-F]{1,4}:(:|\b)|){5}|([\dA-F]{1,4}:){6})((([\dA-F]{1,4}((?!\3)::|:\b|$))|(?!\2\3)){2}|(((2[0-4]|1\d|[1-9])?\d|25[0-5])\.?\b){4})$/i.test(a))return null;if("::"===a)return[0,0,0,0,0,0,0,0];a=a.startsWith("::")?a.replace("::","Z:"):a.replace("::",":Z:");0<a.indexOf(".")?(a=a.replace(/[.]/g,":"),a=a.split(":"),a[a.length-4]=parseInt(a[a.length-4])+256*parseInt(a[a.length-3]),a[a.length-3]=parseInt(a[a.length-2])+256*parseInt(a[a.length-
1]),a=a.slice(0,a.length-2)):a=a.split(":");for(b=c=0;b<a.length;b++)if("string"===typeof a[b])if("Z"===a[b]){for(c=0;c<8-a.length+1;c++)d[b+c]=0;--c}else d[b+c]=zc(parseInt(a[b],16));else d[b+c]=a[b];return[d[1]<<16|d[0],d[3]<<16|d[2],d[5]<<16|d[4],d[7]<<16|d[6]]}
function Ac(a,b,c,d,e){switch(b){case 2:c=xc(c);e&&(w[e>>2]=16);ya[a>>1]=b;w[a+4>>2]=c;ya[a+2>>1]=zc(d);y=[0,(z=0,1<=+Math.abs(z)?0<z?(Math.min(+Math.floor(z/4294967296),4294967295)|0)>>>0:~~+Math.ceil((z-+(~~z>>>0))/4294967296)>>>0:0)];w[a+8>>2]=y[0];w[a+12>>2]=y[1];break;case 10:c=yc(c);e&&(w[e>>2]=28);w[a>>2]=b;w[a+8>>2]=c[0];w[a+12>>2]=c[1];w[a+16>>2]=c[2];w[a+20>>2]=c[3];ya[a+2>>1]=zc(d);w[a+4>>2]=0;w[a+24>>2]=0;break;default:return 5}return 0}var Bc=1,Cc={},Dc={};
function Ec(a){var b=xc(a);if(null!==b)return a;b=yc(a);if(null!==b)return a;Cc[a]?b=Cc[a]:(b=Bc++,assert(65535>b,"exceeded max address mappings of 65535"),b="172.29."+(b&255)+"."+(b&65280),Dc[b]=a,Cc[a]=b);return b}function Fc(a){return(a&255)+"."+(a>>8&255)+"."+(a>>16&255)+"."+(a>>24&255)}
function Gc(a){var b="",c,d=0,e=0,f=0,g=0;a=[a[0]&65535,a[0]>>16,a[1]&65535,a[1]>>16,a[2]&65535,a[2]>>16,a[3]&65535,a[3]>>16];var m=!0;for(c=0;5>c;c++)if(0!==a[c]){m=!1;break}if(m){c=Fc(a[6]|a[7]<<16);if(-1===a[5])return"::ffff:"+c;if(0===a[5])return"0.0.0.0"===c&&(c=""),"0.0.0.1"===c&&(c="1"),"::"+c}for(c=0;8>c;c++)0===a[c]&&(1<c-e&&(g=0),e=c,g++),g>d&&(d=g,f=c-d+1);for(c=0;8>c;c++)1<d&&0===a[c]&&c>=f&&c<f+d?c===f&&(b+=":",0===f&&(b+=":")):(b+=Number(Hc(a[c]&65535)).toString(16),b+=7>c?":":"");return b}
function Ic(a,b){var c=ya[a>>1],d=Hc(Ma[a+2>>1]);switch(c){case 2:if(16!==b)return{ie:28};a=w[a+4>>2];a=Fc(a);break;case 10:if(28!==b)return{ie:28};a=[w[a+8>>2],w[a+12>>2],w[a+16>>2],w[a+20>>2]];a=Gc(a);break;default:return{ie:5}}return{family:c,ke:a,port:d}}function Jc(a,b,c){if(c&&0===a)return null;a=Ic(a,b);if(a.ie)throw new J(a.ie);b=a.ke;a.ke=(Dc[b]?Dc[b]:null)||a.ke;return a}var Kc;ia?Kc=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?Kc=dateNow:Kc=function(){return performance.now()};
function Lc(a,b){Mc=a;Nc=b;if(Oc)if(Pc||(Pc=!0),0==a)Qc=function(){var d=Math.max(0,Rc+b-Kc())|0;setTimeout(Sc,d)};else if(1==a)Qc=function(){Tc(Sc)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);ha?(void 0===h.setImmediates&&(h.setImmediates=[]),h.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}Qc=function(){setImmediate(Sc)}}}
function Uc(a,b,c,d,e){function f(){if(g<Vc){if(!noExitRuntime)try{Wc(Ca)}catch(m){if(!(m instanceof sa))throw m;}return!1}return!0}assert(!Oc,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Oc=a;Xc=d;var g=Vc;Pc=!1;Sc=function(){if(!Ba)if(0<Yc.length){var m=Date.now(),n=Yc.shift();n.fg(n.Te);if(Zc){var r=Zc,q=0==r%1?r-1:Math.floor(r);Zc=n.Cg?q:(8*r+(q+.5))/
9}console.log('main loop blocker "'+n.name+'" took '+(Date.now()-m)+" ms");h.setStatus&&(m=h.statusMessage||"Please wait...",n=Zc,r=$c.Eg,n?n<r?h.setStatus(m+" ("+(r-n)+"/"+r+")"):h.setStatus(m):h.setStatus(""));f()&&setTimeout(Sc,0)}else f()&&(ad=ad+1|0,1==Mc&&1<Nc&&0!=ad%Nc?Qc():(0==Mc&&(Rc=Kc()),Ba||h.preMainLoop&&!1===h.preMainLoop()||(bd(a),h.postMainLoop&&h.postMainLoop()),f()&&("object"===typeof SDL&&SDL.audio&&SDL.audio.rg&&SDL.audio.rg(),Qc())))};e||(b&&0<b?Lc(0,1E3/b):Lc(1,1),Qc());if(c)throw"unwind";
}function bd(a){if(!Ba)try{a()}catch(b){if(!(b instanceof sa)&&"unwind"!==b)throw b&&"object"===typeof b&&b.stack&&k("exception thrown: "+[b,b.stack]),b;}}var Pc=!1,Qc=null,Vc=0,Oc=null,Xc=0,Mc=0,Nc=0,ad=0,Yc=[],$c={},Rc,Sc,Zc,cd=!1,dd=!1,ed=[];
function qc(){function a(){dd=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}h.preloadPlugins||(h.preloadPlugins=[]);if(!fd){fd=!0;try{gd=!0}catch(c){gd=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}hd="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:gd?null:console.log("warning: no BlobBuilder");
kd="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;h.Of||"undefined"!==typeof kd||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),h.Of=!0);h.preloadPlugins.push({canHandle:function(c){return!h.Of&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var g=null;if(gd)try{g=new Blob([c],{type:ld(d)}),g.size!==c.length&&(g=new Blob([(new Uint8Array(c)).buffer],{type:ld(d)}))}catch(r){ua("Blob constructor present but fails: "+
r+"; falling back to blob builder")}g||(g=new hd,g.append((new Uint8Array(c)).buffer),g=g.getBlob());var m=kd.createObjectURL(g),n=new Image;n.onload=function(){assert(n.complete,"Image "+d+" could not be decoded");var r=document.createElement("canvas");r.width=n.width;r.height=n.height;r.getContext("2d").drawImage(n,0,0);h.preloadedImages[d]=r;kd.revokeObjectURL(m);e&&e(c)};n.onerror=function(){console.log("Image "+m+" could not be decoded");f&&f()};n.src=m}});h.preloadPlugins.push({canHandle:function(c){return!h.Ng&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e,f){function g(t){n||(n=!0,h.preloadedAudios[d]=t,e&&e(c))}function m(){n||(n=!0,h.preloadedAudios[d]=new Audio,f&&f())}var n=!1;if(gd){try{var r=new Blob([c],{type:ld(d)})}catch(t){return m()}r=kd.createObjectURL(r);var q=new Audio;q.addEventListener("canplaythrough",function(){g(q)},!1);q.onerror=function(){if(!n){console.log("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var t="",u=0,v=0,
B=0;B<c.length;B++)for(u=u<<8|c[B],v+=8;6<=v;){var x=u>>v-6&63;v-=6;t+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[x]}2==v?(t+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(u&3)<<4],t+="=="):4==v&&(t+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(u&15)<<2],t+="=");q.src="data:audio/x-"+d.substr(-3)+";base64,"+t;g(q)}};q.src=r;md(function(){g(q)})}else return m()}});var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&
b.addEventListener("click",function(c){!dd&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function nd(a,b,c,d){if(b&&h.ze&&a==h.canvas)return h.ze;var e;if(b){var f={antialias:!1,alpha:!1,Kf:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!==typeof od&&(e=pd(a,f)))var m=qd[e].De}else m=a.getContext("2d");if(!m)return null;c&&(b||assert("undefined"===typeof O,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),h.ze=m,b&&rd(e),h.xg=b,ed.forEach(function(n){n()}),qc());return m}var sd=!1,td=void 0,ud=void 0;
function vd(a,b){function c(){cd=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=wd,td&&d.requestPointerLock(),cd=!0,ud?("undefined"!=typeof SDL&&(w[SDL.screen>>2]=Na[SDL.screen>>2]|8388608),xd(h.canvas),yd()):xd(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),ud?("undefined"!=typeof SDL&&(w[SDL.screen>>2]=Na[SDL.screen>>2]&
-8388609),xd(h.canvas),yd()):xd(d));if(h.onFullScreen)h.onFullScreen(cd);if(h.onFullscreen)h.onFullscreen(cd)}td=a;ud=b;"undefined"===typeof td&&(td=!0);"undefined"===typeof ud&&(ud=!1);var d=h.canvas;sd||(sd=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?function(){e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(e.webkitRequestFullScreen?function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);e.requestFullscreen()}
function wd(){if(!cd)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var zd=0;function Tc(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===zd)zd=b+1E3/60;else for(;b+2>=zd;)zd+=1E3/60;setTimeout(a,Math.max(zd-b,0))}}function md(a){setTimeout(function(){bd(a)},1E4)}
function ld(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}function rc(a,b,c){var d="al "+a;na(a,function(e){assert(e,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(e));d&&Ya(d)},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&Xa(d)}var Ad=[];function yd(){var a=h.canvas;Ad.forEach(function(b){b(a.width,a.height)})}
function xd(a,b,c){b&&c?(a.yg=b,a.jg=c):(b=a.yg,c=a.jg);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}ud?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var fd,gd,hd,kd,P=12288,Bd=!1,Cd=0,Dd=0,Ed=0,Q={alpha:!1,depth:!1,stencil:!1,antialias:!1},Fd={},Gd;function Hd(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,g){b.drawElementsInstancedANGLE(c,d,e,f,g)})}
function Id(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Jd(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}var Kd=1,Ld=[],S=[],Md=[],Nd=[],Od=[],T=[],Pd=[],qd=[],Qd=[],Rd={},Sd=4;
function V(a){Td||(Td=a)}function Ud(a){for(var b=Kd++,c=a.length;c<b;c++)a[c]=null;return b}function pd(a,b){a.Ef||(a.Ef=a.getContext,a.getContext=function(d,e){e=a.Ef(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Vd(c,b):0}function Vd(a,b){var c=Ud(qd),d={Ig:c,attributes:b,version:b.Kf,De:a};a.canvas&&(a.canvas.Me=d);qd[c]=d;("undefined"===typeof b.cg||b.cg)&&Wd(d);return c}function rd(a){Xd=qd[a];h.ze=O=Xd&&Xd.De}
function Wd(a){a||(a=Xd);if(!a.lg){a.lg=!0;var b=a.De;Hd(b);Id(b);Jd(b);b.we=b.getExtension("EXT_disjoint_timer_query");b.Mg=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var od={},Td,Xd,Yd=[],Zd=0;function $d(){for(var a=ae.length-1;0<=a;--a)be(a);ae=[];ce=[]}var ce=[];
function de(a,b,c){function d(g,m){if(g.length!=m.length)return!1;for(var n in g)if(g[n]!=m[n])return!1;return!0}for(var e in ce){var f=ce[e];if(f.tf==a&&d(f.xf,c))return}ce.push({tf:a,Pf:b,xf:c});ce.sort(function(g,m){return g.Pf<m.Pf})}function ee(a){for(var b=0;b<ce.length;++b)ce[b].tf==a&&(ce.splice(b,1),--b)}function fe(){if(Zd&&ge.Ee)for(var a=0;a<ce.length;++a){var b=ce[a];ce.splice(a,1);--a;b.tf.apply(null,b.xf)}}var ae=[];
function be(a){var b=ae[a];b.target.removeEventListener(b.oe,b.dg,b.ue);ae.splice(a,1)}function he(a){function b(d){++Zd;ge=a;fe();a.ye(d);fe();--Zd}if(a.ve)a.dg=b,a.target.addEventListener(a.oe,b,a.ue),ae.push(a),ie||(Ra.push($d),ie=!0);else for(var c=0;c<ae.length;++c)ae[c].target==a.target&&ae[c].oe==a.oe&&be(c--)}function je(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}function ke(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}
var le={},ie,ge,me,ne,oe,pe,qe,re,se,te,ue,ve,we,xe,ye={},ze=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function W(a){a=2<a?C(a):a;return ze[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}function Ae(a){var b=Be(),c=Ja(8),d=c+4,e=Ja(a.id.length+1);G(a.id,e,a.id.length+1);if(a=W(e))w[c>>2]=a.width,w[d>>2]=a.height;c=[w[c>>2],w[d>>2]];Ce(b);return c}function De(a,b,c){a=W(a);if(!a)return-4;a.width=b;a.height=c;return 0}
function Ee(a,b,c){if(a.Bg){var d=Be(),e=Ja(a.id.length+1);G(a.id,e,a.id.length+1);De(e,b,c);Ce(d)}else a.width=b,a.height=c}
function Fe(a){function b(){document.fullscreenElement||document.webkitFullscreenElement||document.msFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),Ee(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=m,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=r,a.style.paddingRight=q,a.style.paddingTop=t,a.style.paddingBottom=u,a.style.marginLeft=v,a.style.marginRight=
B,a.style.marginTop=x,a.style.marginBottom=F,document.body.style.margin=U,document.documentElement.style.overflow=ma,document.body.scroll=R,a.style.If=E,a.Me&&a.Me.De.viewport(0,0,d,e),ye.Ue&&I.get(ye.Ue)(37,0,ye.zf))}var c=Ae(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,m=a.style.backgroundColor,n=document.body.style.backgroundColor,r=a.style.paddingLeft,q=a.style.paddingRight,t=a.style.paddingTop,u=a.style.paddingBottom,v=a.style.marginLeft,B=a.style.marginRight,x=a.style.marginTop,F=a.style.marginBottom,
U=document.body.style.margin,ma=document.documentElement.style.overflow,R=document.body.scroll,E=a.style.If;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)}function Ge(a,b,c){a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"}function He(a){return 0>ze.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function Ie(a,b){if(0!=b.sf||0!=b.jf){Fe(a);var c=b.ug?innerWidth:screen.width,d=b.ug?innerHeight:screen.height,e=He(a),f=e.width;e=e.height;var g=Ae(a),m=g[0];g=g[1];3==b.sf?(Ge(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.sf&&(c*g<m*d?(f=g*c/m,Ge(a,(d-f)/2,0),d=f):(f=m*d/g,Ge(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.eg&&(a.style.If="pixelated");
f=2==b.jf?devicePixelRatio:1;0!=b.jf&&(c=c*f|0,d=d*f|0,Ee(a,c,d),a.Me&&a.Me.De.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return ke()?-3:-1;ye=b;b.Ue&&I.get(b.Ue)(37,0,b.zf);return 0}function Je(a){if(a.requestPointerLock)a.requestPointerLock();else if(a.df)a.df();else return document.body.requestPointerLock||document.body.df?-3:-1;return 0}
function Ke(a,b){za[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)za[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)za[a+8*c+528>>3]="object"===typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)w[a+4*c+1040>>2]="object"===typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];w[a+1296>>2]=b.connected;w[a+1300>>2]=b.index;w[a+8>>2]=b.axes.length;w[a+12>>2]=b.buttons.length;G(b.id,a+1304,64);G(b.mapping,a+1368,64)}var Le=[];
function Me(a,b,c,d){for(var e=0;e<a;e++){var f=O[c](),g=f&&Ud(d);f?(f.name=g,d[g]=f):V(1282);w[b+4*e>>2]=g}}function Ne(a,b,c,d,e,f,g,m){b=S[b];if(a=O[a](b,c))d=m&&G(a.name,m,d),e&&(w[e>>2]=d),f&&(w[f>>2]=a.size),g&&(w[g>>2]=a.type)}function Oe(a,b){Na[a>>2]=b;Na[a+4>>2]=(b-Na[a>>2])/4294967296}
function Pe(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&V(1280);return;case 36345:d=0;break;case 34466:var e=O.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=O.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":V(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:V(1280);return}else{if(e instanceof Float32Array||
e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:w[b+4*a>>2]=e[a];break;case 2:A[b+4*a>>2]=e[a];break;case 4:p[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){V(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:V(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:Oe(b,
d);break;case 0:w[b>>2]=d;break;case 2:A[b>>2]=d;break;case 4:p[b>>0]=d?1:0}}else V(1281)}function Qe(a){var b=Ga(a)+1,c=H(b);G(a,c,b);return c}function Re(a,b,c,d){if(c)if(a=S[a],a=O.getUniform(a,a.Se[b]),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:w[c>>2]=a;break;case 2:A[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:w[c+4*b>>2]=a[b];break;case 2:A[c+4*b>>2]=a[b]}else V(1281)}
function Se(a,b,c,d){if(c)if(a=O.getVertexAttrib(a,b),34975==b)w[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:w[c>>2]=a;break;case 2:A[c>>2]=a;break;case 5:w[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:w[c+4*b>>2]=a[b];break;case 2:A[c+4*b>>2]=a[b];break;case 5:w[c+4*b>>2]=Math.fround(a[b])}else V(1281)}
function Te(a,b,c,d,e){a-=5120;a=1==a?D:4==a?w:6==a?A:5==a||28922==a?Na:Ma;var f=31-Math.clz32(a.BYTES_PER_ELEMENT),g=Sd;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<f)+g-1&-g)>>f)}function X(a){var b=O.Zf;if(b){var c=b.Se[a];0<=c&&(b.Se[a]=c=O.getUniformLocation(b,b.Uf[a]+(0<c?"["+c+"]":"")));return c}V(1282)}var Ue=[],Ve=[];
function We(a,b){if(!ke())return-1;a=W(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Zd&&ge.Ee?Ie(a,b):b.bg?(de(Ie,1,[a,b]),1):-2:-3:-4}function Xe(a,b){var c={target:W(2),oe:"beforeunload",ve:b,ye:function(d){d=d||event;var e=I.get(b)(28,0,a);e&&(e=C(e));if(e)return d.preventDefault(),d.returnValue=e},ue:!0};he(c)}
function Ye(a,b,c,d,e,f){ne||(ne=H(256));a={target:W(a),oe:f,ve:d,ye:function(g){g=g||event;var m=g.target.id?g.target.id:"",n=ne;G(je(g.target),n+0,128);G(m,n+128,128);I.get(d)(e,n,b)&&g.preventDefault()},ue:c};he(a)}
function Ze(a,b,c,d,e){pe||(pe=H(280));he({target:a,oe:e,ve:d,ye:function(f){f=f||event;var g=pe,m=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!m;w[g>>2]=n;w[g+4>>2]=ke();var r=n?m:oe,q=r&&r.id?r.id:"";G(je(r),g+8,128);G(q,g+136,128);w[g+264>>2]=r?r.clientWidth:0;w[g+268>>2]=r?r.clientHeight:0;w[g+272>>2]=screen.width;w[g+276>>2]=screen.height;n&&(oe=m);I.get(d)(19,g,b)&&f.preventDefault()},ue:c})}
function $e(a,b,c,d,e){qe||(qe=H(1432));b={target:W(2),Ee:!0,oe:e,ve:c,ye:function(f){f=f||event;var g=qe;Ke(g,f.gamepad);I.get(c)(d,g,a)&&f.preventDefault()},ue:b};he(b)}
function af(a,b,c,d,e,f){re||(re=H(164));a={target:W(a),Ee:!0,oe:f,ve:d,ye:function(g){var m=re,n=m>>2;w[n]=g.location;w[n+1]=g.ctrlKey;w[n+2]=g.shiftKey;w[n+3]=g.altKey;w[n+4]=g.metaKey;w[n+5]=g.repeat;w[n+6]=g.charCode;w[n+7]=g.keyCode;w[n+8]=g.which;G(g.key||"",m+36,32);G(g.code||"",m+68,32);G(g.char||"",m+100,32);G(g.locale||"",m+132,32);I.get(d)(e,m,b)&&g.preventDefault()},ue:c};he(a)}
function bf(a,b,c){a>>=2;w[a]=b.screenX;w[a+1]=b.screenY;w[a+2]=b.clientX;w[a+3]=b.clientY;w[a+4]=b.ctrlKey;w[a+5]=b.shiftKey;w[a+6]=b.altKey;w[a+7]=b.metaKey;ya[2*a+16]=b.button;ya[2*a+17]=b.buttons;w[a+9]=b.movementX;w[a+10]=b.movementY;c=He(c);w[a+11]=b.clientX-c.left;w[a+12]=b.clientY-c.top}function cf(a,b,c,d,e,f){se||(se=H(64));a=W(a);he({target:a,Ee:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,oe:f,ve:d,ye:function(g){g=g||event;bf(se,g,a);I.get(d)(e,se,b)&&g.preventDefault()},ue:c})}
function df(a,b,c,d,e){te||(te=H(260));he({target:a,oe:e,ve:d,ye:function(f){f=f||event;var g=te,m=document.pointerLockElement||document.Oe||document.Jg||document.Hf;w[g>>2]=!!m;var n=m&&m.id?m.id:"";G(je(m),g+4,128);G(n,g+132,128);I.get(d)(20,g,b)&&f.preventDefault()},ue:c})}
function ef(a,b,c,d){ue||(ue=H(36));a=W(a);he({target:a,oe:"resize",ve:d,ye:function(e){e=e||event;if(e.target==a){var f=document.body;if(f){var g=ue;w[g>>2]=e.detail;w[g+4>>2]=f.clientWidth;w[g+8>>2]=f.clientHeight;w[g+12>>2]=innerWidth;w[g+16>>2]=innerHeight;w[g+20>>2]=outerWidth;w[g+24>>2]=outerHeight;w[g+28>>2]=pageXOffset;w[g+32>>2]=pageYOffset;I.get(d)(10,g,b)&&e.preventDefault()}}},ue:c})}
function ff(a,b,c,d,e,f){ve||(ve=H(1684));a=W(a);he({target:a,Ee:"touchstart"==f||"touchend"==f,oe:f,ve:d,ye:function(g){for(var m={},n=g.touches,r=0;r<n.length;++r){var q=n[r];m[q.identifier]=q}n=g.changedTouches;for(r=0;r<n.length;++r)q=n[r],q.mg=1,m[q.identifier]=q;n=g.targetTouches;for(r=0;r<n.length;++r)m[n[r].identifier].qg=1;n=ve;q=n>>2;w[q+1]=g.ctrlKey;w[q+2]=g.shiftKey;w[q+3]=g.altKey;w[q+4]=g.metaKey;q+=5;var t=He(a),u=0;for(r in m){var v=m[r];w[q]=v.identifier;w[q+1]=v.screenX;w[q+2]=v.screenY;
w[q+3]=v.clientX;w[q+4]=v.clientY;w[q+5]=v.pageX;w[q+6]=v.pageY;w[q+7]=v.mg;w[q+8]=v.qg;w[q+9]=v.clientX-t.left;w[q+10]=v.clientY-t.top;q+=13;if(31<++u)break}w[n>>2]=u;I.get(d)(e,n,b)&&g.preventDefault()},ue:c})}function gf(a,b,c){var d=ze[1];we||(we=H(8));he({target:d,oe:"visibilitychange",ve:c,ye:function(e){e=e||event;var f=we,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);w[f>>2]=document.hidden;w[f+4>>2]=g;I.get(c)(21,f,a)&&e.preventDefault()},ue:b})}
function hf(a,b,c,d){xe||(xe=H(96));he({target:a,Ee:!0,oe:"wheel",ve:d,ye:function(e){e=e||event;var f=xe;bf(f,e,a);za[f+64>>3]=e.deltaX;za[f+72>>3]=e.deltaY;za[f+80>>3]=e.deltaZ;w[f+88>>2]=e.deltaMode;I.get(d)(9,f,b)&&e.preventDefault()},ue:c})}var jf={};
function kf(){if(!lf){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in jf)a[b]=jf[b];var c=[];for(b in a)c.push(b+"="+a[b]);lf=c}return lf}var lf,Y={};
function mf(a){mf.buffer||(mf.buffer=H(256),Y["0"]="Success",Y["-1"]="Invalid value for 'ai_flags' field",Y["-2"]="NAME or SERVICE is unknown",Y["-3"]="Temporary failure in name resolution",Y["-4"]="Non-recoverable failure in name res",Y["-6"]="'ai_family' not supported",Y["-7"]="'ai_socktype' not supported",Y["-8"]="SERVICE not supported for 'ai_socktype'",Y["-10"]="Memory allocation failure",Y["-11"]="System error returned in 'errno'",Y["-12"]="Argument buffer overflow");var b="Unknown error";a in
Y&&(255<Y[a].length?b="Message too long":b=Y[a]);Ka(b,mf.buffer);return mf.buffer}function Lb(a,b,c,d){a||(a=this);this.parent=a;this.Be=a.Be;this.Pe=null;this.id=Cb++;this.name=b;this.mode=c;this.he={};this.ge={};this.rdev=d}
Object.defineProperties(Lb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},og:{get:function(){return L(this.mode)}},ng:{get:function(){return 8192===(this.mode&61440)}}});fc();Db=Array(4096);Sb(K,"/");Ub("/tmp");Ub("/home");Ub("/home/web_user");
(function(){Ub("/dev");qb(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Vb("/dev/null",259);pb(1280,tb);pb(1536,ub);Vb("/dev/tty",1280);Vb("/dev/tty1",1536);var a=mb();mc("/dev","random",a);mc("/dev","urandom",a);Ub("/dev/shm");Ub("/dev/shm/tmp")})();
(function(){Ub("/proc");var a=Ub("/proc/self");Ub("/proc/self/fd");Sb({Be:function(){var b=wb(a,"fd",16895,73);b.he={lookup:function(c,d){var e=Bb[+d];if(!e)throw new J(8);c={parent:null,Be:{Mf:"fake"},he:{readlink:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();h.FS_createPath=jc;h.FS_createDataFile=lc;h.FS_createPreloadedFile=pc;h.FS_createLazyFile=oc;h.FS_createDevice=mc;h.FS_unlink=Xb;h.requestFullscreen=function(a,b){vd(a,b)};h.requestAnimationFrame=function(a){Tc(a)};
h.setCanvasSize=function(a,b,c){xd(h.canvas,a,b);c||yd()};h.pauseMainLoop=function(){Qc=null;Vc++};h.resumeMainLoop=function(){Vc++;var a=Mc,b=Nc,c=Oc;Oc=null;Uc(c,0,!1,Xc,!0);Lc(a,b);Qc()};h.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};h.createContext=function(a,b,c,d){return nd(a,b,c,d)};for(var O,Z=0;32>Z;++Z)Le.push(Array(Z));var nf=new Float32Array(288);
for(Z=0;288>Z;++Z)Ue[Z]=nf.subarray(0,Z+1);var of=new Int32Array(288);for(Z=0;288>Z;++Z)Ve[Z]=of.subarray(0,Z+1);function sb(a){var b=Array(Ga(a)+1);a=Fa(a,b,0,b.length);b.length=a;return b}
var sf={eb:function(a,b,c,d){try{for(var e=0,f=b?w[b>>2]:0,g=b?w[b+4>>2]:0,m=c?w[c>>2]:0,n=c?w[c+4>>2]:0,r=d?w[d>>2]:0,q=d?w[d+4>>2]:0,t=0,u=0,v=0,B=0,x=0,F=0,U=(b?w[b>>2]:0)|(c?w[c>>2]:0)|(d?w[d>>2]:0),ma=(b?w[b+4>>2]:0)|(c?w[c+4>>2]:0)|(d?w[d+4>>2]:0),R=0;R<a;R++){var E=1<<R%32;if(32>R?U&E:ma&E){var dc=Bb[R];if(!dc)throw new J(8);var ec=5;dc.ge.ff&&(ec=dc.ge.ff(dc));ec&1&&(32>R?f&E:g&E)&&(32>R?t|=E:u|=E,e++);ec&4&&(32>R?m&E:n&E)&&(32>R?v|=E:B|=E,e++);ec&2&&(32>R?r&E:q&E)&&(32>R?x|=E:F|=E,e++)}}b&&
(w[b>>2]=t,w[b+4>>2]=u);c&&(w[c>>2]=v,w[c+4>>2]=B);d&&(w[d>>2]=x,w[d+4>>2]=F);return e}catch(jd){return"undefined"!==typeof M&&jd instanceof J||l(jd),-jd.ie}},Va:function(a,b,c){try{var d=wc(a),e=d.te.accept(d);b&&Ac(b,e.family,Ec(e.re),e.xe,c);return e.stream.fd}catch(f){return"undefined"!==typeof M&&f instanceof J||l(f),-f.ie}},jb:function(a,b){try{a=C(a);if(b&-8)var c=-28;else{var d;(d=Gb(a,{Ne:!0}).node)?(a="",b&4&&(a+="r"),b&2&&(a+="w"),b&1&&(a+="x"),c=a&&Kb(d,a)?-2:0):c=-44}return c}catch(e){return"undefined"!==
typeof M&&e instanceof J||l(e),-e.ie}},Za:function(a,b,c){try{var d=wc(a),e=Jc(b,c);d.te.bind(d,e.ke,e.port);return 0}catch(f){return"undefined"!==typeof M&&f instanceof J||l(f),-f.ie}},Xa:function(a,b,c){try{var d=wc(a),e=Jc(b,c);d.te.connect(d,e.ke,e.port);return 0}catch(f){return"undefined"!==typeof M&&f instanceof J||l(f),-f.ie}},c:function(a,b,c){tc=c;try{var d=vc(a);switch(b){case 0:var e=uc();return 0>e?-28:Zb(d.path,d.flags,0,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=
uc(),d.flags|=e,0;case 12:return e=uc(),ya[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return w[pf()>>2]=28,-1;default:return-28}}catch(f){return"undefined"!==typeof M&&f instanceof J||l(f),-f.ie}},hb:function(a,b){try{var c=vc(a);return sc(c.path,b)}catch(d){return"undefined"!==typeof M&&d instanceof J||l(d),-d.ie}},Ua:function(a,b,c){try{var d=wc(a);if(!d.re)return-53;Ac(b,d.family,Ec(d.re),d.xe,c);return 0}catch(e){return"undefined"!==typeof M&&e instanceof J||l(e),-e.ie}},
Ra:function(a,b,c,d,e){try{var f=wc(a);return 1===b&&4===c?(w[d>>2]=f.error,w[e>>2]=4,f.error=null,0):-50}catch(g){return"undefined"!==typeof M&&g instanceof J||l(g),-g.ie}},U:function(a,b,c){tc=c;try{var d=vc(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var e=uc();return w[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=uc();if(!d.ge.Ye)throw new J(59);return d.ge.Ye(d,
b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:l("bad ioctl syscall "+b)}}catch(f){return"undefined"!==typeof M&&f instanceof J||l(f),-f.ie}},Wa:function(a,b){try{var c=wc(a);c.te.listen(c,b);return 0}catch(d){return"undefined"!==typeof M&&d instanceof J||l(d),-d.ie}},V:function(a,b,c){tc=c;try{var d=C(a),e=c?uc():0;return Zb(d,b,e).fd}catch(f){return"undefined"!==typeof M&&f instanceof J||l(f),-f.ie}},Sa:function(a,b,c,d,e,f){try{var g=wc(a),m=g.te.Rf(g,c);if(!m)return 0;
e&&Ac(e,g.family,Ec(m.ke),m.port,f);D.set(m.buffer,b);return m.buffer.byteLength}catch(n){return"undefined"!==typeof M&&n instanceof J||l(n),-n.ie}},Ta:function(a,b,c,d,e,f){try{var g=wc(a),m=Jc(e,f,!0);return m?g.te.Tf(g,p,b,c,m.ke,m.port):cc(g.stream,p,b,c)}catch(n){return"undefined"!==typeof M&&n instanceof J||l(n),-n.ie}},Qa:function(){return-50},T:function(a,b,c){try{return N.createSocket(a,b,c).stream.fd}catch(d){return"undefined"!==typeof M&&d instanceof J||l(d),-d.ie}},fb:function(a,b){try{return a=
C(a),sc(a,b)}catch(c){return"undefined"!==typeof M&&c instanceof J||l(c),-c.ie}},ld:function(a){Wc(a)},a:function(){l()},k:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=Kc();else return w[pf()>>2]=28,-1;w[b>>2]=a/1E3|0;w[b+4>>2]=a%1E3*1E6|0;return 0},Ca:function(){l("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking")},Ka:function(){l("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking")},
Sb:function(){l("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking")},Q:function(){l("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking")},Hb:function(a){if(12448==a)return P=12288,1;P=12300;return 0},xc:function(a,b,c,d,e){if(62E3!=a)P=12296,c=0;else{if(b)for(;;){a=w[b>>2];if(12321==a)Q.alpha=0<w[b+4>>2];else if(12325==a)Q.depth=0<w[b+4>>2];else if(12326==
a)Q.stencil=0<w[b+4>>2];else if(12337==a)a=w[b+4>>2],Q.antialias=0<a;else if(12338==a)a=w[b+4>>2],Q.antialias=1==a;else if(12544==a)Q.Kg=12547!=w[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(w[e>>2]=1),c&&0<d&&(w[c>>2]=62002),P=12288,c=1):(P=12300,c=0)}return c},Ja:function(a,b,c,d){if(62E3!=a)return P=12296,0;for(a=1;;){b=w[d>>2];if(12440==b)a=w[d+4>>2];else if(12344==b)break;else return P=12292,0;d+=8}if(2!=a)return P=12293,0;Q.Kf=a-1;Q.Lg=0;Gd=pd(h.canvas,Q);if(0!=Gd)return P=12288,rd(Gd),
h.xg=!0,ed.forEach(function(e){e()}),rd(null),62004;P=12297;return 0},Ma:function(a,b){if(62E3!=a)return P=12296,0;if(62002!=b)return P=12293,0;P=12288;return 62006},La:function(a,b){if(62E3!=a)return P=12296,0;if(62004!=b)return P=12294,0;a=Gd;Xd===qd[a]&&(Xd=null);if("object"===typeof le)for(var c=qd[a].De.canvas,d=0;d<ae.length;++d)ae[d].target!=c||be(d--);qd[a]&&qd[a].De.canvas&&(qd[a].De.canvas.Me=void 0);qd[a]=null;P=12288;Cd==b&&(Cd=0);return 1},Na:function(a,b){if(62E3!=a)return P=12296,0;
if(62006!=b)return P=12301,1;Dd==b&&(Dd=0);Ed==b&&(Ed=0);P=12288;return 1},Ic:function(a,b,c,d){if(62E3!=a)return P=12296,0;if(62002!=b)return P=12293,0;if(!d)return P=12300,0;P=12288;switch(c){case 12320:return w[d>>2]=Q.alpha?32:24,1;case 12321:return w[d>>2]=Q.alpha?8:0,1;case 12322:return w[d>>2]=8,1;case 12323:return w[d>>2]=8,1;case 12324:return w[d>>2]=8,1;case 12325:return w[d>>2]=Q.depth?24:0,1;case 12326:return w[d>>2]=Q.stencil?8:0,1;case 12327:return w[d>>2]=12344,1;case 12328:return w[d>>
2]=62002,1;case 12329:return w[d>>2]=0,1;case 12330:return w[d>>2]=4096,1;case 12331:return w[d>>2]=16777216,1;case 12332:return w[d>>2]=4096,1;case 12333:return w[d>>2]=0,1;case 12334:return w[d>>2]=0,1;case 12335:return w[d>>2]=12344,1;case 12337:return w[d>>2]=Q.antialias?4:0,1;case 12338:return w[d>>2]=Q.antialias?1:0,1;case 12339:return w[d>>2]=4,1;case 12340:return w[d>>2]=12344,1;case 12341:case 12342:case 12343:return w[d>>2]=-1,1;case 12345:case 12346:return w[d>>2]=0,1;case 12347:return w[d>>
2]=0,1;case 12348:return w[d>>2]=1;case 12349:case 12350:return w[d>>2]=0,1;case 12351:return w[d>>2]=12430,1;case 12352:return w[d>>2]=4,1;case 12354:return w[d>>2]=0,1;default:return P=12292,0}},X:function(){P=12288;return 62E3},Ia:function(){return P},bc:function(a,b,c){if(62E3==a)return b&&(w[b>>2]=1),c&&(w[c>>2]=4),Bd=!0,P=12288,1;P=12296;return 0},Oa:function(a,b,c,d){if(62E3!=a)return P=12296,0;if(0!=d&&62004!=d)return P=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return P=12301,0;rd(d?Gd:null);
Cd=d;Ed=b;Dd=c;P=12288;return 1},Ha:function(a,b){if(62E3!=a)return P=12296,0;P=12288;if(Fd[b])return Fd[b];switch(b){case 12371:a=Ha("Emscripten");break;case 12372:a=Ha("1.4 Emscripten EGL");break;case 12373:a=Ha("");break;case 12429:a=Ha("OpenGL_ES");break;default:return P=12300,0}return Fd[b]=a},Ya:function(){if(Bd)if(h.ze)if(h.ze.isContextLost())P=12302;else return P=12288,1;else P=12290;else P=12289;return 0},gb:function(a,b){if(62E3!=a)return P=12296,0;0==b?Lc(0,0):Lc(1,b);P=12288;return 1},
mc:function(a){if(62E3!=a)return P=12296,0;Ed=Dd=Cd=0;Bd=!1;P=12288;return 1},wb:function(){P=12288;return 1},lb:function(){P=12288;return 1},b:function(a,b,c){Yd.length=0;var d;for(c>>=2;d=D[b++];)(d=105>d)&&c&1&&c++,Yd.push(d?za[c++>>1]:w[c]),++c;return fb[a].apply(null,Yd)},Da:function(){if(!ke())return-1;ee(Ie);var a=ze[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},Ga:function(){ee(Je);
if(document.exitPointerLock)document.exitPointerLock();else if(document.ne)document.ne();else return-1;return 0},i:function(){return"number"===typeof devicePixelRatio&&devicePixelRatio||1},e:function(a,b,c){a=W(a);if(!a)return-4;a=He(a);za[b>>3]=a.width;za[c>>3]=a.height;return 0},u:function(a,b){if(0>a||a>=me.length)return-5;if(!me[a])return-7;Ke(b,me[a]);return 0},ib:function(){return D.length},Ba:function(){return me.length},ha:function(a){O.activeTexture(a)},ga:function(a,b){O.attachShader(S[a],
T[b])},xa:function(a,b){O.we.beginQueryEXT(a,Qd[b])},fa:function(a,b,c){O.bindAttribLocation(S[a],b,C(c))},ea:function(a,b){O.bindBuffer(a,Ld[b])},da:function(a,b){O.bindFramebuffer(a,Md[b])},ca:function(a,b){O.bindRenderbuffer(a,Nd[b])},ba:function(a,b){O.bindTexture(a,Od[b])},pa:function(a){O.bindVertexArray(Pd[a])},aa:function(a,b,c,d){O.blendColor(a,b,c,d)},$:function(a){O.blendEquation(a)},_:function(a,b){O.blendEquationSeparate(a,b)},Z:function(a,b){O.blendFunc(a,b)},Qd:function(a,b,c,d){O.blendFuncSeparate(a,
b,c,d)},Pd:function(a,b,c,d){O.bufferData(a,c?D.subarray(c,c+b):b,d)},Od:function(a,b,c,d){O.bufferSubData(a,b,D.subarray(d,d+c))},Nd:function(a){return O.checkFramebufferStatus(a)},Md:function(a){O.clear(a)},Ld:function(a,b,c,d){O.clearColor(a,b,c,d)},Kd:function(a){O.clearDepth(a)},Jd:function(a){O.clearStencil(a)},Id:function(a,b,c,d){O.colorMask(!!a,!!b,!!c,!!d)},Hd:function(a){O.compileShader(T[a])},Gd:function(a,b,c,d,e,f,g,m){O.compressedTexImage2D(a,b,c,d,e,f,m?D.subarray(m,m+g):null)},Fd:function(a,
b,c,d,e,f,g,m,n){O.compressedTexSubImage2D(a,b,c,d,e,f,g,n?D.subarray(n,n+m):null)},Ed:function(a,b,c,d,e,f,g,m){O.copyTexImage2D(a,b,c,d,e,f,g,m)},Dd:function(a,b,c,d,e,f,g,m){O.copyTexSubImage2D(a,b,c,d,e,f,g,m)},Cd:function(){var a=Ud(S),b=O.createProgram();b.name=a;b.af=b.Ze=b.$e=0;b.uf=1;S[a]=b;return a},Bd:function(a){var b=Ud(T);T[b]=O.createShader(a);return b},Ad:function(a){O.cullFace(a)},zd:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Ld[d];e&&(O.deleteBuffer(e),e.name=0,Ld[d]=
null)}},yd:function(a,b){for(var c=0;c<a;++c){var d=w[b+4*c>>2],e=Md[d];e&&(O.deleteFramebuffer(e),e.name=0,Md[d]=null)}},xd:function(a){if(a){var b=S[a];b?(O.deleteProgram(b),b.name=0,S[a]=null):V(1281)}},za:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Qd[d];e&&(O.we.deleteQueryEXT(e),Qd[d]=null)}},vd:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Nd[d];e&&(O.deleteRenderbuffer(e),e.name=0,Nd[d]=null)}},ud:function(a){if(a){var b=T[a];b?(O.deleteShader(b),T[a]=null):V(1281)}},td:function(a,
b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Od[d];e&&(O.deleteTexture(e),e.name=0,Od[d]=null)}},oa:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2];O.deleteVertexArray(Pd[d]);Pd[d]=null}},sd:function(a){O.depthFunc(a)},rd:function(a){O.depthMask(!!a)},qd:function(a,b){O.depthRange(a,b)},pd:function(a,b){O.detachShader(S[a],T[b])},od:function(a){O.disable(a)},nd:function(a){O.disableVertexAttribArray(a)},md:function(a,b,c){O.drawArrays(a,b,c)},ka:function(a,b,c,d){O.drawArraysInstanced(a,b,c,d)},
la:function(a,b){for(var c=Le[a],d=0;d<a;d++)c[d]=w[b+4*d>>2];O.drawBuffers(c)},kd:function(a,b,c,d){O.drawElements(a,b,c,d)},ja:function(a,b,c,d,e){O.drawElementsInstanced(a,b,c,d,e)},jd:function(a){O.enable(a)},id:function(a){O.enableVertexAttribArray(a)},wa:function(a){O.we.endQueryEXT(a)},hd:function(){O.finish()},gd:function(){O.flush()},fd:function(a,b,c,d){O.framebufferRenderbuffer(a,b,c,Nd[d])},ed:function(a,b,c,d,e){O.framebufferTexture2D(a,b,c,Od[d],e)},dd:function(a){O.frontFace(a)},cd:function(a,
b){Me(a,b,"createBuffer",Ld)},ad:function(a,b){Me(a,b,"createFramebuffer",Md)},Aa:function(a,b){for(var c=0;c<a;c++){var d=O.we.createQueryEXT();if(!d){for(V(1282);c<a;)w[b+4*c++>>2]=0;break}var e=Ud(Qd);d.name=e;Qd[e]=d;w[b+4*c>>2]=e}},$c:function(a,b){Me(a,b,"createRenderbuffer",Nd)},_c:function(a,b){Me(a,b,"createTexture",Od)},na:function(a,b){Me(a,b,"createVertexArray",Pd)},bd:function(a){O.generateMipmap(a)},Zc:function(a,b,c,d,e,f,g){Ne("getActiveAttrib",a,b,c,d,e,f,g)},Yc:function(a,b,c,d,
e,f,g){Ne("getActiveUniform",a,b,c,d,e,f,g)},Xc:function(a,b,c,d){a=O.getAttachedShaders(S[a]);var e=a.length;e>b&&(e=b);w[c>>2]=e;for(b=0;b<e;++b)w[d+4*b>>2]=T.indexOf(a[b])},Wc:function(a,b){return O.getAttribLocation(S[a],C(b))},Vc:function(a,b){Pe(a,b,4)},Uc:function(a,b,c){c?w[c>>2]=O.getBufferParameter(a,b):V(1281)},Tc:function(){var a=O.getError()||Td;Td=0;return a},Sc:function(a,b){Pe(a,b,2)},Rc:function(a,b,c,d){a=O.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||
a instanceof WebGLTexture)a=a.name|0;w[d>>2]=a},Qc:function(a,b){Pe(a,b,0)},Oc:function(a,b,c,d){a=O.getProgramInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?G(a,d,b):0;c&&(w[c>>2]=b)},Pc:function(a,b,c){if(c)if(a>=Kd)V(1281);else if(a=S[a],35716==b)a=O.getProgramInfoLog(a),null===a&&(a="(unknown error)"),w[c>>2]=a.length+1;else if(35719==b){if(!a.af)for(b=0;b<O.getProgramParameter(a,35718);++b)a.af=Math.max(a.af,O.getActiveUniform(a,b).name.length+1);w[c>>2]=a.af}else if(35722==b){if(!a.Ze)for(b=
0;b<O.getProgramParameter(a,35721);++b)a.Ze=Math.max(a.Ze,O.getActiveAttrib(a,b).name.length+1);w[c>>2]=a.Ze}else if(35381==b){if(!a.$e)for(b=0;b<O.getProgramParameter(a,35382);++b)a.$e=Math.max(a.$e,O.getActiveUniformBlockName(a,b).length+1);w[c>>2]=a.$e}else w[c>>2]=O.getProgramParameter(a,b);else V(1281)},ra:function(a,b,c){if(c){a=O.we.getQueryObjectEXT(Qd[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;Oe(c,d)}else V(1281)},ta:function(a,b,c){if(c){a=O.we.getQueryObjectEXT(Qd[a],b);var d;"boolean"==
typeof a?d=a?1:0:d=a;w[c>>2]=d}else V(1281)},qa:function(a,b,c){if(c){a=O.we.getQueryObjectEXT(Qd[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;Oe(c,d)}else V(1281)},sa:function(a,b,c){if(c){a=O.we.getQueryObjectEXT(Qd[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;w[c>>2]=d}else V(1281)},ua:function(a,b,c){c?w[c>>2]=O.we.getQueryEXT(a,b):V(1281)},Nc:function(a,b,c){c?w[c>>2]=O.getRenderbufferParameter(a,b):V(1281)},Lc:function(a,b,c,d){a=O.getShaderInfoLog(T[a]);null===a&&(a="(unknown error)");b=0<b&&
d?G(a,d,b):0;c&&(w[c>>2]=b)},Kc:function(a,b,c,d){a=O.getShaderPrecisionFormat(a,b);w[c>>2]=a.rangeMin;w[c+4>>2]=a.rangeMax;w[d>>2]=a.precision},Jc:function(a,b,c,d){if(a=O.getShaderSource(T[a]))b=0<b&&d?G(a,d,b):0,c&&(w[c>>2]=b)},Mc:function(a,b,c){c?35716==b?(a=O.getShaderInfoLog(T[a]),null===a&&(a="(unknown error)"),w[c>>2]=a?a.length+1:0):35720==b?(a=O.getShaderSource(T[a]),w[c>>2]=a?a.length+1:0):w[c>>2]=O.getShaderParameter(T[a],b):V(1281)},Hc:function(a){var b=Rd[a];if(!b){switch(a){case 7939:b=
O.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Qe(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=O.getParameter(a))||V(1280);b=b&&Qe(b);break;case 7938:b=Qe("OpenGL ES 2.0 ("+O.getParameter(7938)+")");break;case 35724:b=O.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Qe(b);break;default:V(1280)}Rd[a]=b}return b},Gc:function(a,b,c){c?
A[c>>2]=O.getTexParameter(a,b):V(1281)},Fc:function(a,b,c){c?w[c>>2]=O.getTexParameter(a,b):V(1281)},Cc:function(a,b){function c(v){return"]"==v.slice(-1)&&v.lastIndexOf("[")}b=C(b);if(a=S[a]){var d=a.Se,e=a.wg,f,g=0,m=b,n=c(b);if(!d)for(a.Se=d={},a.Uf={},f=0;f<O.getProgramParameter(a,35718);++f){var r=O.getActiveUniform(a,f);var q=r.name;r=r.size;var t=c(q);t=0<t?q.slice(0,t):q;var u=a.uf;a.uf+=r;e[t]=[r,u];for(q=0;q<r;++q)d[u]=q,a.Uf[u++]=t}0<n&&(g=parseInt(b.slice(n+1))>>>0,m=b.slice(0,n));if((e=
e[m])&&g<e[0]&&(g+=e[1],d[g]=d[g]||O.getUniformLocation(a,b)))return g}else V(1281);return-1},Ec:function(a,b,c){Re(a,b,c,2)},Dc:function(a,b,c){Re(a,b,c,0)},zc:function(a,b,c){c?w[c>>2]=O.getVertexAttribOffset(a,b):V(1281)},Bc:function(a,b,c){Se(a,b,c,2)},Ac:function(a,b,c){Se(a,b,c,5)},yc:function(a,b){O.hint(a,b)},wc:function(a){return(a=Ld[a])?O.isBuffer(a):0},vc:function(a){return O.isEnabled(a)},uc:function(a){return(a=Md[a])?O.isFramebuffer(a):0},tc:function(a){return(a=S[a])?O.isProgram(a):
0},ya:function(a){return(a=Qd[a])?O.we.isQueryEXT(a):0},sc:function(a){return(a=Nd[a])?O.isRenderbuffer(a):0},rc:function(a){return(a=T[a])?O.isShader(a):0},qc:function(a){return(a=Od[a])?O.isTexture(a):0},ma:function(a){return(a=Pd[a])?O.isVertexArray(a):0},pc:function(a){O.lineWidth(a)},oc:function(a){a=S[a];O.linkProgram(a);a.Se=0;a.wg={}},nc:function(a,b){3317==a&&(Sd=b);O.pixelStorei(a,b)},lc:function(a,b){O.polygonOffset(a,b)},va:function(a,b){O.we.queryCounterEXT(Qd[a],b)},kc:function(a,b,
c,d,e,f,g){(g=Te(f,e,c,d,g))?O.readPixels(a,b,c,d,e,f,g):V(1280)},jc:function(){},ic:function(a,b,c,d){O.renderbufferStorage(a,b,c,d)},hc:function(a,b){O.sampleCoverage(a,!!b)},gc:function(a,b,c,d){O.scissor(a,b,c,d)},fc:function(){V(1280)},ec:function(a,b,c,d){for(var e="",f=0;f<b;++f){var g=d?w[d+4*f>>2]:-1;e+=C(w[c+4*f>>2],0>g?void 0:g)}O.shaderSource(T[a],e)},dc:function(a,b,c){O.stencilFunc(a,b,c)},cc:function(a,b,c,d){O.stencilFuncSeparate(a,b,c,d)},ac:function(a){O.stencilMask(a)},$b:function(a,
b){O.stencilMaskSeparate(a,b)},_b:function(a,b,c){O.stencilOp(a,b,c)},Zb:function(a,b,c,d){O.stencilOpSeparate(a,b,c,d)},Yb:function(a,b,c,d,e,f,g,m,n){O.texImage2D(a,b,c,d,e,f,g,m,n?Te(m,g,d,e,n):null)},Xb:function(a,b,c){O.texParameterf(a,b,c)},Wb:function(a,b,c){O.texParameterf(a,b,A[c>>2])},Vb:function(a,b,c){O.texParameteri(a,b,c)},Ub:function(a,b,c){O.texParameteri(a,b,w[c>>2])},Tb:function(a,b,c,d,e,f,g,m,n){var r=null;n&&(r=Te(m,g,e,f,n));O.texSubImage2D(a,b,c,d,e,f,g,m,r)},Rb:function(a,
b){O.uniform1f(X(a),b)},Qb:function(a,b,c){if(288>=b)for(var d=Ue[b-1],e=0;e<b;++e)d[e]=A[c+4*e>>2];else d=A.subarray(c>>2,c+4*b>>2);O.uniform1fv(X(a),d)},Pb:function(a,b){O.uniform1i(X(a),b)},Ob:function(a,b,c){if(288>=b)for(var d=Ve[b-1],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);O.uniform1iv(X(a),d)},Nb:function(a,b,c){O.uniform2f(X(a),b,c)},Mb:function(a,b,c){if(144>=b)for(var d=Ue[2*b-1],e=0;e<2*b;e+=2)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2];else d=A.subarray(c>>2,c+8*b>>2);
O.uniform2fv(X(a),d)},Lb:function(a,b,c){O.uniform2i(X(a),b,c)},Kb:function(a,b,c){if(144>=b)for(var d=Ve[2*b-1],e=0;e<2*b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2];else d=w.subarray(c>>2,c+8*b>>2);O.uniform2iv(X(a),d)},Jb:function(a,b,c,d){O.uniform3f(X(a),b,c,d)},Ib:function(a,b,c){if(96>=b)for(var d=Ue[3*b-1],e=0;e<3*b;e+=3)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2],d[e+2]=A[c+(4*e+8)>>2];else d=A.subarray(c>>2,c+12*b>>2);O.uniform3fv(X(a),d)},Gb:function(a,b,c,d){O.uniform3i(X(a),b,c,d)},Fb:function(a,
b,c){if(96>=b)for(var d=Ve[3*b-1],e=0;e<3*b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2];else d=w.subarray(c>>2,c+12*b>>2);O.uniform3iv(X(a),d)},Eb:function(a,b,c,d,e){O.uniform4f(X(a),b,c,d,e)},Db:function(a,b,c){if(72>=b){var d=Ue[4*b-1],e=A;c>>=2;for(var f=0;f<4*b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=A.subarray(c>>2,c+16*b>>2);O.uniform4fv(X(a),d)},Cb:function(a,b,c,d,e){O.uniform4i(X(a),b,c,d,e)},Bb:function(a,b,c){if(72>=b)for(var d=
Ve[4*b-1],e=0;e<4*b;e+=4)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2],d[e+3]=w[c+(4*e+12)>>2];else d=w.subarray(c>>2,c+16*b>>2);O.uniform4iv(X(a),d)},Ab:function(a,b,c,d){if(72>=b)for(var e=Ue[4*b-1],f=0;f<4*b;f+=4)e[f]=A[d+4*f>>2],e[f+1]=A[d+(4*f+4)>>2],e[f+2]=A[d+(4*f+8)>>2],e[f+3]=A[d+(4*f+12)>>2];else e=A.subarray(d>>2,d+16*b>>2);O.uniformMatrix2fv(X(a),!!c,e)},zb:function(a,b,c,d){if(32>=b)for(var e=Ue[9*b-1],f=0;f<9*b;f+=9)e[f]=A[d+4*f>>2],e[f+1]=A[d+(4*f+4)>>2],e[f+2]=A[d+
(4*f+8)>>2],e[f+3]=A[d+(4*f+12)>>2],e[f+4]=A[d+(4*f+16)>>2],e[f+5]=A[d+(4*f+20)>>2],e[f+6]=A[d+(4*f+24)>>2],e[f+7]=A[d+(4*f+28)>>2],e[f+8]=A[d+(4*f+32)>>2];else e=A.subarray(d>>2,d+36*b>>2);O.uniformMatrix3fv(X(a),!!c,e)},yb:function(a,b,c,d){if(18>=b){var e=Ue[16*b-1],f=A;d>>=2;for(var g=0;g<16*b;g+=16){var m=d+g;e[g]=f[m];e[g+1]=f[m+1];e[g+2]=f[m+2];e[g+3]=f[m+3];e[g+4]=f[m+4];e[g+5]=f[m+5];e[g+6]=f[m+6];e[g+7]=f[m+7];e[g+8]=f[m+8];e[g+9]=f[m+9];e[g+10]=f[m+10];e[g+11]=f[m+11];e[g+12]=f[m+12];e[g+
13]=f[m+13];e[g+14]=f[m+14];e[g+15]=f[m+15]}}else e=A.subarray(d>>2,d+64*b>>2);O.uniformMatrix4fv(X(a),!!c,e)},xb:function(a){a=S[a];O.useProgram(a);O.Zf=a},vb:function(a){O.validateProgram(S[a])},ub:function(a,b){O.vertexAttrib1f(a,b)},tb:function(a,b){O.vertexAttrib1f(a,A[b>>2])},sb:function(a,b,c){O.vertexAttrib2f(a,b,c)},rb:function(a,b){O.vertexAttrib2f(a,A[b>>2],A[b+4>>2])},qb:function(a,b,c,d){O.vertexAttrib3f(a,b,c,d)},pb:function(a,b){O.vertexAttrib3f(a,A[b>>2],A[b+4>>2],A[b+8>>2])},ob:function(a,
b,c,d,e){O.vertexAttrib4f(a,b,c,d,e)},nb:function(a,b){O.vertexAttrib4f(a,A[b>>2],A[b+4>>2],A[b+8>>2],A[b+12>>2])},ia:function(a,b){O.vertexAttribDivisor(a,b)},mb:function(a,b,c,d,e,f){O.vertexAttribPointer(a,b,c,!!d,e,f)},kb:function(a,b,c,d){O.viewport(a,b,c,d)},o:function(){return 0},_a:function(a,b,c){D.copyWithin(a,b,b+c)},Ea:function(a,b,c){return We(a,{sf:w[c>>2],jf:w[c+4>>2],eg:w[c+8>>2],bg:b,Ue:w[c+12>>2],zf:w[c+16>>2]})},R:function(a,b){a=W(a);return a?a.requestPointerLock||a.df?Zd&&ge.Ee?
Je(a):b?(de(Je,2,[a]),1):-2:-1:-4},$a:function(){l("OOM")},v:function(){return(me=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():null)?0:-1},w:function(a,b,c){if("undefined"===typeof onbeforeunload)return-1;if(1!==c)return-5;Xe(a,b);return 0},I:function(a,b,c,d){Ye(a,b,c,d,12,"blur");return 0},f:De,m:function(a,b,c){a=W(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},J:function(a,b,c,d){Ye(a,b,c,d,13,"focus");return 0},
z:function(a,b,c,d){if(!ke())return-1;a=W(a);if(!a)return-4;Ze(a,b,c,d,"fullscreenchange");Ze(a,b,c,d,"webkitfullscreenchange");return 0},t:function(a,b,c){if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;$e(a,b,c,26,"gamepadconnected");return 0},s:function(a,b,c){if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;$e(a,b,c,27,"gamepaddisconnected");return 0},C:function(a,b,c,d){af(a,b,c,d,2,"keydown");return 0},A:function(a,b,c,d){af(a,b,c,d,1,"keypress");return 0},B:function(a,
b,c,d){af(a,b,c,d,3,"keyup");return 0},Rd:function(a,b,c){a=I.get(a);Uc(a,b,c)},O:function(a,b,c,d){cf(a,b,c,d,5,"mousedown");return 0},M:function(a,b,c,d){cf(a,b,c,d,33,"mouseenter");return 0},L:function(a,b,c,d){cf(a,b,c,d,34,"mouseleave");return 0},P:function(a,b,c,d){cf(a,b,c,d,8,"mousemove");return 0},N:function(a,b,c,d){cf(a,b,c,d,6,"mouseup");return 0},D:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.ne||document.body.Oe||document.body.df))return-1;
a=W(a);if(!a)return-4;df(a,b,c,d,"pointerlockchange");df(a,b,c,d,"mozpointerlockchange");df(a,b,c,d,"webkitpointerlockchange");df(a,b,c,d,"mspointerlockchange");return 0},y:function(a,b,c,d){ef(a,b,c,d);return 0},E:function(a,b,c,d){ff(a,b,c,d,25,"touchcancel");return 0},G:function(a,b,c,d){ff(a,b,c,d,23,"touchend");return 0},F:function(a,b,c,d){ff(a,b,c,d,24,"touchmove");return 0},H:function(a,b,c,d){ff(a,b,c,d,22,"touchstart");return 0},x:function(a,b,c){if(!ze[1])return-4;gf(a,b,c);return 0},K:function(a,
b,c,d){a=W(a);return"undefined"!==typeof a.onwheel?(hf(a,b,c,d),0):-1},n:function(){throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},db:function(a){for(var b=Kc();Kc()-b<a;);},bb:function(a,b){try{var c=0;kf().forEach(function(d,e){var f=b+c;w[a+4*e>>2]=f;Ka(d,f);c+=d.length+1});return 0}catch(d){return"undefined"!==typeof M&&d instanceof J||l(d),d.ie}},cb:function(a,b){try{var c=kf();w[a>>2]=c.length;var d=0;c.forEach(function(e){d+=
e.length+1});w[b>>2]=d;return 0}catch(e){return"undefined"!==typeof M&&e instanceof J||l(e),e.ie}},q:function(a){Wc(a)},j:function(a){try{var b=vc(a);ac(b);return 0}catch(c){return"undefined"!==typeof M&&c instanceof J||l(c),c.ie}},ab:function(a,b){try{var c=vc(a);p[b>>0]=c.tty?2:L(c.mode)?3:40960===(c.mode&61440)?7:4;return 0}catch(d){return"undefined"!==typeof M&&d instanceof J||l(d),d.ie}},W:function(a,b,c,d){try{a:{for(var e=vc(a),f=a=0;f<c;f++){var g=w[b+(8*f+4)>>2],m=e,n=w[b+8*f>>2],r=g,q=void 0,
t=p;if(0>r||0>q)throw new J(28);if(null===m.fd)throw new J(8);if(1===(m.flags&2097155))throw new J(8);if(L(m.node.mode))throw new J(31);if(!m.ge.read)throw new J(28);var u="undefined"!==typeof q;if(!u)q=m.position;else if(!m.seekable)throw new J(70);var v=m.ge.read(m,t,n,r,q);u||(m.position+=v);var B=v;if(0>B){var x=-1;break a}a+=B;if(B<g)break}x=a}w[d>>2]=x;return 0}catch(F){return"undefined"!==typeof M&&F instanceof J||l(F),F.ie}},Pa:function(a,b,c,d,e){try{var f=vc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=
a||9007199254740992<=a)return-61;bc(f,a,d);y=[f.position>>>0,(z=f.position,1<=+Math.abs(z)?0<z?(Math.min(+Math.floor(z/4294967296),4294967295)|0)>>>0:~~+Math.ceil((z-+(~~z>>>0))/4294967296)>>>0:0)];w[e>>2]=y[0];w[e+4>>2]=y[1];f.mf&&0===a&&0===d&&(f.mf=null);return 0}catch(g){return"undefined"!==typeof M&&g instanceof J||l(g),g.ie}},p:function(a,b,c,d){try{a:{for(var e=vc(a),f=a=0;f<c;f++){var g=cc(e,p,w[b+8*f>>2],w[b+(8*f+4)>>2],void 0);if(0>g){var m=-1;break a}a+=g}m=a}w[d>>2]=m;return 0}catch(n){return"undefined"!==
typeof M&&n instanceof J||l(n),n.ie}},h:mf,Fa:function(a,b,c,d){function e(t,u,v,B,x,F){var U=10===t?28:16;x=10===t?Gc(x):Fc(x);U=H(U);x=Ac(U,t,x,F);assert(!x);x=H(32);w[x+4>>2]=t;w[x+8>>2]=u;w[x+12>>2]=v;w[x+24>>2]=B;w[x+20>>2]=U;w[x+16>>2]=10===t?28:16;w[x+28>>2]=0;return x}var f=0,g=0,m=0,n=0,r=0,q=0;c&&(m=w[c>>2],n=w[c+4>>2],r=w[c+8>>2],q=w[c+12>>2]);r&&!q&&(q=2===r?17:6);!r&&q&&(r=17===q?2:1);0===q&&(q=6);0===r&&(r=1);if(!a&&!b)return-2;if(m&-1088||0!==c&&w[c>>2]&2&&!a)return-1;if(m&32)return-2;
if(0!==r&&1!==r&&2!==r)return-7;if(0!==n&&2!==n&&10!==n)return-6;if(b&&(b=C(b),g=parseInt(b,10),isNaN(g)))return m&1024?-2:-8;if(!a)return 0===n&&(n=2),0===(m&1)&&(2===n?f=qf(2130706433):f=[0,0,0,1]),a=e(n,r,q,null,f,g),w[d>>2]=a,0;a=C(a);f=xc(a);if(null!==f)if(0===n||2===n)n=2;else if(10===n&&m&8)f=[0,0,qf(65535),f],n=10;else return-2;else if(f=yc(a),null!==f)if(0===n||10===n)n=10;else return-2;if(null!=f)return a=e(n,r,q,a,f,g),w[d>>2]=a,0;if(m&4)return-2;a=Ec(a);f=xc(a);0===n?n=2:10===n&&(f=[0,
0,qf(65535),f]);a=e(n,r,q,null,f,g);w[d>>2]=a;return 0},g:function(a){var b=Date.now();w[a>>2]=b/1E3|0;w[a+4>>2]=b%1E3*1E3|0;return 0},r:function(){return 6},Y:function(){return 28},S:function(){},d:function(){return 0},wd:function(){return 0},l:function(a){0!==a&&rf(a,0,16);return 0}};
(function(){function a(e){h.asm=e.exports;Aa=h.asm.Sd;La=e=Aa.buffer;h.HEAP8=p=new Int8Array(e);h.HEAP16=ya=new Int16Array(e);h.HEAP32=w=new Int32Array(e);h.HEAPU8=D=new Uint8Array(e);h.HEAPU16=Ma=new Uint16Array(e);h.HEAPU32=Na=new Uint32Array(e);h.HEAPF32=A=new Float32Array(e);h.HEAPF64=za=new Float64Array(e);I=h.asm.Wd;Pa.unshift(h.asm.Td);Ya("wasm-instantiate")}function b(e){a(e.instance)}function c(e){return cb().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){k("failed to asynchronously prepare wasm: "+
f);l(f)})}var d={a:sf};Xa("wasm-instantiate");if(h.instantiateWasm)try{return h.instantiateWasm(d,a)}catch(e){return k("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return wa||"function"!==typeof WebAssembly.instantiateStreaming||Za()||$a.startsWith("file://")||"function"!==typeof fetch?c(b):fetch($a,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){k("wasm streaming compile failed: "+f);k("falling back to ArrayBuffer instantiation");
return c(b)})})})();return{}})();h.___wasm_call_ctors=function(){return(h.___wasm_call_ctors=h.asm.Td).apply(null,arguments)};var rf=h._memset=function(){return(rf=h._memset=h.asm.Ud).apply(null,arguments)};h._main=function(){return(h._main=h.asm.Vd).apply(null,arguments)};
var pf=h.___errno_location=function(){return(pf=h.___errno_location=h.asm.Xd).apply(null,arguments)},Hc=h._ntohs=function(){return(Hc=h._ntohs=h.asm.Yd).apply(null,arguments)},zc=h._htons=function(){return(zc=h._htons=h.asm.Zd).apply(null,arguments)},H=h._malloc=function(){return(H=h._malloc=h.asm._d).apply(null,arguments)},qf=h._htonl=function(){return(qf=h._htonl=h.asm.$d).apply(null,arguments)},Be=h.stackSave=function(){return(Be=h.stackSave=h.asm.ae).apply(null,arguments)},Ce=h.stackRestore=function(){return(Ce=
h.stackRestore=h.asm.be).apply(null,arguments)},Ja=h.stackAlloc=function(){return(Ja=h.stackAlloc=h.asm.ce).apply(null,arguments)};h.dynCall_jiji=function(){return(h.dynCall_jiji=h.asm.de).apply(null,arguments)};h.dynCall_ji=function(){return(h.dynCall_ji=h.asm.ee).apply(null,arguments)};h.addRunDependency=Xa;h.removeRunDependency=Ya;h.FS_createPath=jc;h.FS_createDataFile=lc;h.FS_createPreloadedFile=pc;h.FS_createLazyFile=oc;h.FS_createDevice=mc;h.FS_unlink=Xb;var tf;
function sa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Wa=function uf(){tf||vf();tf||(Wa=uf)};
function vf(a){function b(){if(!tf&&(tf=!0,h.calledRun=!0,!Ba)){h.noFSInit||hc||(hc=!0,fc(),h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?mc("/dev","stdin",h.stdin):Wb("/dev/tty","/dev/stdin"),h.stdout?mc("/dev","stdout",null,h.stdout):Wb("/dev/tty","/dev/stdout"),h.stderr?mc("/dev","stderr",null,h.stderr):Wb("/dev/tty1","/dev/stderr"),Zb("/dev/stdin",0),Zb("/dev/stdout",1),Zb("/dev/stderr",1));N.root=Sb(N,null);hb(Pa);Eb=!1;hb(Qa);if(h.onRuntimeInitialized)h.onRuntimeInitialized();
if(wf){var c=a,d=h._main;c=c||[];var e=c.length+1,f=Ja(4*(e+1));w[f>>2]=Ia(da);for(var g=1;g<e;g++)w[(f>>2)+g]=Ia(c[g-1]);w[(f>>2)+e]=0;try{var m=d(e,f);Wc(m,!0)}catch(n){n instanceof sa||"unwind"==n||((c=n)&&"object"===typeof n&&n.stack&&(c=[n,n.stack]),k("exception thrown: "+c),ea(1,n))}finally{}}if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;)c=h.postRun.shift(),Sa.unshift(c);hb(Sa)}}a=a||ca;if(!(0<Ua)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=
[h.preRun]);h.preRun.length;)Ta();hb(Oa);0<Ua||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);b()},1)):b())}}h.run=vf;function Wc(a,b){Ca=a;if(!b||!noExitRuntime||0!==a){if(!noExitRuntime){if(h.onExit)h.onExit(a);Ba=!0}ea(a,new sa(a))}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var wf=!0;h.noInitialRun&&(wf=!1);vf();
